### ISSUE TITLE
Partial Mocking

### ISSUE THREAD

**Issue by hlegius** [phpspec/prophecy#101]
Hi guys,
There is any news about Partial Mocking supported in v1 ?
Here is an example:

``` php
function it_will_call_b_and_delegate_to_a() {
  $this->a('foo', 'bar')->shouldBeCalled();
  $this->b('bar');
}
```

``` php
public function a($foo, $bar) {
  // do a
}

public function b($bar) {
  // do something to create foo
  $this->a($foo, $bar);
}
```

With partial mocks will be possible to mocking `$this` public methods.

**Comment by malkusch** [comment]
> we cannot mock functions

We [can](https://github.com/php-mock/php-mock). And I just wanted to write an integration package for Prophecy… but without a prophecy of an abstract class which would leave the implemented methods, it's just a pain for me :(

**Comment by edsonmedina** [comment]
I know I'm late to this (closed) debate, and I'm not going to try to defend any of the sides. Just a quick question.

Am I right to assume that not being able to partial mock (by design) means that you recommend we never use `$this->someMethod()`?

**Comment by stof** [comment]
@edsonmedina you can call other methods of the same interface, but this should be unknown for the outside i.e. you don't consider the other method of the same class as a collaborator which should be mocked.
Using a partial mock is almost always a sign of mixing multiple responsibilities in the class (as you want to test only of them them by mocking the other)

**Comment by edsonmedina** [comment]
Ok, so the recommendation is we should test the class just by using the public API as a seam.

> Using a partial mock is almost always a sign of mixing multiple responsibilities in the class (as you want to test only of them them by mocking the other)

I see. I do agree that's usually the case. Protected / private methods are usually an indicator that something should be extracted into a different class.

I do understand where the opposition is coming from though.
It is a quite radical position. Not bad, but radical.

Thanks for the enlightenment.

**Comment by stof** [comment]
Well, nothing prevents you to use a PHPUnit mock for the case where you need a partial mock, and Prophecy for all other mocks.
Prophecy is an opinionated tool (as is PhpSpec). Making it hard or impossible to work with badly designed code is actually a feature in PhpSpec, not an issue (even though some people may not agree, in which case they can totally use a different tool).

**Comment by edsonmedina** [comment]
Maybe that should be phrased in prophecy's github page.

It took me a while (and quite a bit of confusion / frustration) googling around until I realized I wasn't doing anything wrong, and it was a limitation by design.

If you mention you don't do partial mocks, you might save some people the same frustration.
