### ISSUE TITLE
Error when collaborator has a final class

### ISSUE THREAD

**Issue by leevigraham** [phpspec/prophecy#102]
If I pass a collaborator that has a final class I'm specking, phpspec gives me the error.

`could not reflect class Doctrine\ORM\Query as it is marked final.`

In my scenario I'm trying to pass `Doctrine\ORM\Query` as a parameter in my spec method. My spec is testing a class that decorates the `Doctrine\ORM\Tools\Pagination\Paginator`

The example `let()` method:

``` php

// use …

class DoctrinePaginatorDecoratorSpec extends ObjectBehavior
{
    public function let(Paginator $paginator, Query $query)
    {
        $paginator->getQuery()->willReturn($query);
        $paginator->count()->willReturn(95);

        $this->beConstructedWith($paginator);
    }
}
```

results in:

```
Nsm/DoctrinePaginator/DoctrinePaginatorDecorator
28  ! is initializable (51ms)
could not reflect class Doctrine\ORM\Query as it is marked final.
```

Is this expected behaviour for `final class…` if so is there a way to work around it?

I did work around this by creating a `new Query()` in the method but this seems very wrong. Example:

``` php

// use …

class DoctrinePaginatorDecoratorSpec extends ObjectBehavior
{
    public function let(Paginator $paginator, EntityManager $entityManager)
    {
        $paginator->getQuery()->willReturn(new Query($entityManager->getWrappedObject()));
        $paginator->count()->willReturn(95);

        $this->beConstructedWith($paginator);
        $this->setMaxPerPageNumber(10);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType('Nsm\DoctrinePaginator\DoctrinePaginatorDecorator');
    }
}
```

This may be similar to #54 (hence the similar title).

Any ideas?

**Comment by eddiejaoude** [comment]
@leevigraham I have a similar issue, but when using `new Query($em->getWrappedObject())` as you did, I get the following error:

```
      method call:
        Double\Doctrine\ORM\EntityManager\P52->getConfiguration()
      was not expected.
```

When I mock that out `getConfiguration`, it was followed by more errors, did you come across this issue or have any ideas? Thanks

**Comment by sstok** [comment]
Mocking with Doctrine ORM is not easy, and it can actually hide some bugs as you are not using an 
implementation, once you start working with some of its internals its better to just use a small boilerplate to get a real set-up for testing. Thats what I did in https://github.com/rollerworks/rollerworks-search-doctrine-orm/blob/master/tests/OrmTestCase.php#L64-L103 which is largely based on the Doctrine ORM functional tests.

**Comment by stof** [comment]
In any case, mocking the Doctrine layer in your own tests looks like a mistake: the test will pass according to what **you** consider as being the Doctrine behavior. But there is no guarantee that your test doubles behaves the same way than Doctrine actually does (and given the number of complex cases in Doctrine, you can be quite sure you will make mistakes at some points), and no way for you to discover that your code breaks in case the Doctrine behavior changes (because of the previous point).
If your class integrates with an external library, you should be writing integration tests instead.

**Comment by eddiejaoude** [comment]
> If your class integrates with an external library, you should be writing integration tests instead.

Thanks for the clarification @stof :+1:
