### ISSUE TITLE
Not possible to Mock SimpleXmlElement

### ISSUE THREAD

**Issue by henrikbjorn** [phpspec/prophecy#131]
Because SimpleXmlElement defines is constructor as final it is not possible to mock it as a collaborator when using php spec.

```
PHP Fatal error:  Cannot override final method SimpleXMLElement::__construct()
```

``` php
function it_gets_nodes_from_xml_element(SimpleXmlElement $element) {
}
```

**Comment by stof** [comment]
Mocking such class which you don't control seems a small IMO. It should be an integration test instead (to be sure your code works against the real SimpleXmlElement API, not only against what you *think* this API is)

**Comment by everzet** [comment]
What @stof said.
