### ISSUE TITLE
Fatal error when mocking reference returning interface methods 

### ISSUE THREAD

**Issue by edsonmedina** [phpspec/prophecy#139]
Example:

    interface A
    {
        public function &foo ($x, $y, $z);
    }
    
    $prophet = new Prophecy\Prophet;
    
    $x = $prophet->prophesize();
    $x->willImplement ('A');
    $z = $x->reveal();

This will throw a PHP fatal error:

    PHP Fatal error:  Declaration of Double\A\P1::blah() must be compatible with & A::blah($x, $y, $z) in /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2
    PHP Stack trace:
    PHP   1. {main}() /home/edson/tmp/test.php:0
    PHP   2. Prophecy\Prophecy\ObjectProphecy->reveal() /home/edson/tmp/test.php:14
    PHP   3. Prophecy\Doubler\LazyDouble->getInstance() /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Prophecy/ObjectProphecy.php:105
    PHP   4. Prophecy\Doubler\Doubler->double() /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Doubler/LazyDouble.php:122
    PHP   5. Prophecy\Doubler\Doubler->createDoubleClass() /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:105
    PHP   6. Prophecy\Doubler\Generator\ClassCreator->create() /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:142
    PHP   7. eval() /home/edson/tmp/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php:49
    
    shell returned 255

**Comment by edsonmedina** [comment]
Possibly related to this?
https://bugs.php.net/bug.php?id=48019

**Comment by aik099** [comment]
@edsonmedina , I recommend you adding `Closes #1234` in the PR description instead of mentioning that issue in the commit message itself. This way GitHub will properly link PR to the issue.
