### ISSUE TITLE
Could not load package phpspec/prophecy in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"

### ISSUE THREAD

**Issue by survex** [phpspec/prophecy#153]
Your package has [doctrine/instantiator: ^1.0.2] which is recognized as invalid dependency, please fix this issue as soon as possible.

**Comment by sstok** [comment]
Update your composer version `composer self-update`
This also works on Travis, unless you are using `sudo: false` in your config.

#149 #148

**Comment by joshcrawmer4** [comment]
Thank you for this solution. It worked perfect!

**Comment by uchsarath** [comment]
That's much help. Thanks 1+
