### ISSUE TITLE
Promise determined by arguments are not instance-aware

### ISSUE THREAD

**Issue by dantleech** [phpspec/prophecy#157]
When trying to return different promises for 2 or more calls to the same method with different instances of an identitical object the results are always that of the last promise to have been made.

````php
$this->resolver = $this->prophesize('DTL\Component\Content\Form\ContentViewResolver');

$this->document1 = new StructureDocument();
$this->document2 = new StructureDocument();

$this->contentView1 = $this->prophesize('DTL\Component\Content\Form\ContentView');
$this->contentView1->getValue()->willReturn('one');
$this->contentView2 = $this->prophesize('DTL\Component\Content\Form\ContentView');
$this->contentView2->getValue()->willReturn('two');

$this->resolver->resolve($this->document1)->willReturn($this->contentView1->reveal());
$this->resolver->resolve($this->document2)->willReturn($this->contentView2->reveal());

echo $this->resolver->resolve($this->document1)->getValue(); // two
echo $this->resolver->resolve($this->document2)->getValue(); // two
````

However:

````php
// ...

$this->document2->setTitle('foo');

// ...
echo $this->resolver->resolve($this->document1)->getValue(); // one
echo $this->resolver->resolve($this->document2)->getValue(); // two
````

**Comment by everzet** [comment]
Because by default arguments aren't checked for identity, they're checked for equality. If you want to check for identity, you need to explicitly use [`Argument::is(...)` token](https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Argument.php#L194-L197).

**Comment by dantleech** [comment]
Would it not make sense to check by identity if the arguments are objects? I think it would be more intuitive..

**Comment by everzet** [comment]
@dantleech I'm not sure. I wouldn't go as far as to say it is more intuitive. Based on my experience memory-based object identity is harder to reason about than value-based one.

Anyways change to the logic here would be a major BC break now.
