### ISSUE TITLE
PHPUnit: "This test did not perform any assertions"

### ISSUE THREAD

**Issue by edsonmedina** [phpspec/prophecy#158]
When using prophecy in phpunit in strict mode, my tests get flagged as risky and I get the warning "This test did not perform any assertions".

I've got expectations set, and they're passing. All the tests are passing, but I get the warning.

**Comment by sstok** [comment]
Thats because PHPUnit keeps track of any assertions that that are set. Note that Mocks are also assertions as they expect (assert) to be called. Prophecy (currently) works outside of this system and so there no actual assertions, and thus you get these warnings.

**Comment by everzet** [comment]
This problem seems to have nothing to do with this particular codebase. Feel free to reopen if I'm wrong.

**Comment by edsonmedina** [comment]
So do you think it's not worthy to make prophecy interact with PHPUnit?
I'd be willing to do it.

**Comment by everzet** [comment]
Prophecy codebase doesn't know or assume anything about PhpSpec - a framework it technically was created for. Why would it want to know anything about PhpUnit?

PhpUnit is an owner of integration between PhpUnit and Prophecy, not Prophecy.

**Comment by edsonmedina** [comment]
Fair enough.

**Comment by edsonmedina** [comment]
It seems someone beat me to it.
https://github.com/sebastianbergmann/phpunit/wiki/ChangeLog-for-PHPUnit-4.5

**Comment by stof** [comment]
@edsonmedina and the https://github.com/phpspec/prophecy-phpunit repo which provides the integration for older versions of PHPUnit also counts assertions in the dev version.
