### ISSUE TITLE
HHVM supports mocking of final classes and methods

### ISSUE THREAD

**Issue by dwlnetnl** [phpspec/prophecy#171]
Please support HHVM's __MockClass attribute. "This attribute allows final methods and final classes to be overridden." See https://github.com/facebook/FBMock for an implementation in a mock library and the HHVM source for the implementation in the runtime. (https://github.com/facebook/hhvm/blob/eafd55a09e9f264e6ba6eab1fe3727f045d78c8e/hphp/hhbbc/class-util.h#L59)

**Comment by Nek-** [comment]
IMO this will not be done as the behavior is not supported for PHP. But I openned an issue about that: #197

**Comment by stof** [comment]
Well, actually, the HHVM feature may be used on HHVM to allow mocking final classes on HHVM (it would still be impossible on PHP)
