### ISSUE TITLE
ObjectProphecy::addMethodProphecy return self object for chaining method

### ISSUE THREAD

**Issue by gusdecool** [phpspec/prophecy#175]
`ObjectProphecy::addMethodProphecy()` currently return void. 
Will be nice if it return `ObjectProphecy` so it can be chained.

**Comment by everzet** [comment]
Not really interested in chaining this kind of methods. Why do you need it?

**Comment by stof** [comment]
@gusdecool what is your use case for calling this method directly ?

**Comment by gusdecool** [comment]
Hi, thanks for your response and sorry for my late reply

I use addMethodProphecy like this

```php
$donation = $this->prophesize('AwesomeNameSpace\DonationObject');
$donation->addMethodProphecy(
    (new MethodProphecy($donation, 'getQuantity', []))->willReturn(1)
);
$donation->addMethodProphecy(
    (new MethodProphecy($donation, 'getDonationType', []))->willReturn('paypal')
);
```

If able to use chaining method, the code will be more clean.

Note i didn't like the code styling of using it like this

```php
$donation = $this->prophesize('AwesomeNameSpace\DonationObject');
$donation->getQuantity()->willReturn(1);
$donation->getDonationType()->willReturn(1);
```

As this will trigger warning in IDE for unknown method name, that's the reason i prefer use `addMethodProphecy()`

**Comment by everzet** [comment]
I'm sorry, your use-case sound pretty niche to me.
