### ISSUE TITLE
composer breakage due to caret operator

### ISSUE THREAD

**Issue by hairmare** [phpspec/prophecy#176]
This package is breaking composer installs that use a tagged version of composer left and right.

The breaking change was introduced in 7a914a5 where the caret operator was first used.

Many peoples builds are breaking because phpunit is pulling in prophecy in a version that uses the caret operator and thus depends on an unreleased version of composer.

Right now the only way to mitigate this is to use a recent build of composer when using phpunit. I'm sure this was not the intended behaviour when using a caret operator in ``composer.json``.

Right now I see 2 ways to fix this:
* remove the caret from ``composer.json`` (ie. use ``>=x.y <x+1`` for now) and remove the offending release from packagist.
* get composer to do a new tagged release.

I'm aware the both solutions are not ideal. The first one is a no-no since you would be removing already tagged software and I expect that to break other things all over the place. It does seem zf2 is doing something similar though.

The second solution won't work since prophecy is not in control of composer releases. You could raise it on composer/composer#3779, composer/composer#3877 and composer/satis#200 though. I believe most of these are breaking due to prophecy (or in the first case zf2 which has acknowledged and reported the issue).

To make this future proof it would be nice if you could also start testing against a tagged version of composer. I see you're running ``composer install --no-interaction --prefer-source`` on travis and that is not helping here at all.

**Comment by stof** [comment]
@hairmare Travis runs the version of Composer available at the time it updates its build images. given that caret operator is 4 months old, Travis already supports it.

Removing our releases from Packagist and Github (which is necessary so that Packagist does not add them again on next push) is not a solution IMO.
The right solution is for Composer to finally release a new version: https://twitter.com/seldaek/status/581530843535052801

**Comment by hairmare** [comment]
@stof Yes, composer should release alpha10. Consider this a warning since composer self-update has been rolling out the feature long enough for bugreports pertaining to this to end up here (due to the fact that prophecy is one of the earliest adopters of the feature as it seems).

**Comment by mdance** [comment]
Is there a workaround for the time being? This issue has completely halted development for me

**Comment by GrahamCampbell** [comment]
Use a newer release of composer. This feature has been available in composer for about 4 months.

**Comment by mdance** [comment]
When I run composer self-update it says:
You are already using composer version 4d134ce8a2aacb9566fee8deb8c514248fd2a983.

**Comment by stof** [comment]
@mdance 4d134ce8a2aacb9566fee8deb8c514248fd2a983 is the latest composer version, which supports the caret operator. So I see 2 possible cases:

- the composer phar you self-update is not the same than the one you use to run the installation
- the error you get is not related to this issue at all

**Comment by stof** [comment]
Closing as Composer alpha10 has been released
