### ISSUE TITLE
Unable to mock symfony UploadedFile

### ISSUE THREAD

**Issue by totaltrash** [phpspec/prophecy#184]
When i try to mock an UploadedFile:

```php
/**
 * @param   Symfony\Component\HttpFoundation\File\UploadedFile  $uploadedFile
 */
function it_does_something($uploadedFile)
{
    $this->doSomething($uploadedFile);
}
```

I get:

```
35  - it does something
      exception [exc:Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException("The file "" does not exist")] has been thrown.

       0 vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/File.php:41
         throw new Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException("The file "" does not exis...")
       1 vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/UploadedFile.php:100
         Symfony\Component\HttpFoundation\File\File->__construct(null, true)
       2 vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code:6
         Symfony\Component\HttpFoundation\File\UploadedFile->__construct(null, null, null, null, null, null)
       3 [internal]
         Double\Symfony\Component\HttpFoundation\File\UploadedFile\P4->__construct()
       4 vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:113
         ReflectionClass->newInstance()
       5 vendor/phpspec/prophecy/src/Prophecy/Doubler/LazyDouble.php:122
         Prophecy\Doubler\Doubler->double([obj:ReflectionClass], [array:0])
       6 vendor/phpspec/prophecy/src/Prophecy/Prophecy/ObjectProphecy.php:114
         Prophecy\Doubler\LazyDouble->getInstance()
       7 src/Advtafe/Bundle/FilerBundle/spec/Advtafe/Bundle/FilerBundle/Factory/FileFactorySpec.php:43
         spec\Advtafe\Bundle\FilerBundle\Factory\FileFactorySpec->doSomething([obj:PhpSpec\Wrapper\Collaborator])
       8 [internal]
         spec\Advtafe\Bundle\FilerBundle\Factory\FileFactorySpec->it_does_something([obj:PhpSpec\Wrapper\Collaborator])
```

I found this too: http://stackoverflow.com/questions/29640748/unit-test-uploadedfile-php-in-phpspec, but I couldn't find anything here. 

Any ideas?

**Comment by everzet** [comment]
### The real answer

Your pain comes from the fact that you're breaking 2 cornerstone rules of using mock objects:

- [Mock Roles, not Objects](http://www.jmock.org/oopsla2004.pdf)
- [Don't Mock What You Don't Own](http://blog.8thlight.com/eric-smith/2011/10/27/thats-not-yours.html)

### The longer, technical answer

`UploadedFile` extends `SplFileInfo`, which is not really a PHP class, but a C API exposed through PHP to look like a normal class. This particular C API has a very interesting behaviour - if you do not pass a valid file name to the parent constructor of the `SplFileInfo`, calling any method of this class will segfault. 

That behaviour is the reason for [this classpatch](https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Doubler/ClassPatch/SplFileInfoPatch.php), which still does not cover every possible edge case (as you can see in your case). Solution: Do not mock objects you do not own.

**Comment by totaltrash** [comment]
Thanks as always for your detailed response. I have some reading and relearning to do!

One thing that i can't quite work out is that the stub UploadedFile fails to even construct, so not really an edge case (from what i can tell). My SUT is doing nothing with the UploadedFile stub (no methods are called), it is just receiving the UploadedFile. The exact same code works great with a File object (which also extends SplFileInfo).
