### ISSUE TITLE
Cannot prophesize Fuel Validator

### ISSUE THREAD

**Issue by sagikazarmark** [phpspec/prophecy#185]
I am trying to prophesize [Fuel\Validation\Validator](https://github.com/fuelphp/validation/blob/master/src/Validator.php) and I get the following error (using it in phpspec):

```
could not double `Fuel\Validation\Validator` and implement interfaces: [Prophecy\Prophecy\ProphecySubjectInterface, Prophecy\Doubler\Generator\ReflectionInterface].
```

The relevant PHP error is:

```
Parse error: syntax error, unexpected '(', expecting identifier (T_STRING) in PROJECT_PATH/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 54
```

I found that the generated double has a function without name and I don't know why:

``` php
public  function () {
return $this->getProphecy()->makeProphecyMethodCall(__FUNCTION__, func_get_args());
}
```

After a few hours of debugging, I cannot find the reason. Any help would be appreciated.

**Comment by stof** [comment]
@sagikazarmark the issue is that this class has invalid ``@method`` phpdoc, which confuse Prophecy when mocking them.

**Comment by sagikazarmark** [comment]
@stof what does invalid mean? Is it invalid syntax?

**Comment by ciaranmcnulty** [comment]
http://phpdoc.org/docs/latest/references/phpdoc/tags/method.html

```
@method [return type] [name]([[type] [parameter]<, ...>]) [<description>]
```

Parentheses are required, for one thing.

Prophecy probably should handle this case more cleanly.

**Comment by sagikazarmark** [comment]
Thanks
