### ISSUE TITLE
Could not load package phpspec/prophecy in packgist.org 

### ISSUE THREAD

**Issue by diego3** [phpspec/prophecy#186]
I am trying to install phpUnit via composer, but the composer throws an error/exception with the message of title this issue.

the execption is : UnexpectedValueException - Could not parse version constraint ^1.0.2: invalid version string "^1.0.2" 

my composer is not the error origin, i can install and update a lot of projects.

**Comment by diego3** [comment]
I think that jus update this part of the composer file is ok to work

```json
"require": {
        "phpdocumentor/reflection-docblock": "~2.0",
        "sebastian/comparator":              "~1.1",
        "doctrine/instantiator":             "^1.0.2" ---> to ---> "~1.0.2"
    },
```

**Comment by sstok** [comment]
This has been reported multiple times, update your composer installation with: `composer self-update`

**Comment by GrahamCampbell** [comment]
@diego3 Your change is wrong anyway. They are not the same as each other.

**Comment by diego3** [comment]
@sstok great... thanks guys... it works to me now

**Comment by stof** [comment]
Closing this. Composer supports the ``^`` operator since December 2014, so it is fine to use it. Using such outdated Composer is not a good idea (and changing it now would not solve the issue btw, unless we delete all our existing releases using this operator, and this won't happen).
