### ISSUE TITLE
Provide implementation of ObjectProphecy::__call() also as none magic method like 'has()'

### ISSUE THREAD

**Issue by hhilbert** [phpspec/prophecy#202]
Modern IDE's like PHPStorm provide code validation and autocompletion. Using __call to provide not implemented methods breaks this. I have no chance to workaround this.
I can cast a variable to be ObjectProphecy or my interface but the result of for instance increment (int) does not understand willReturn().
So if you could provide a method like 'has' or 'willReceive' or whatever you find suitable. This would allow users to choose between nice magic method calls:

    $oProphecy
        ->increment()
        ->willReturn(1);

 or better support in IDE:

    $oProphecy
        ->has('increment', [])
        ->willReturn(1);

Autocompletion also saves a lot of time and prevents typing mistakes.

**Comment by stof** [comment]
Well, methods supported by ``__call`` depend on methods defined in the class being doubled. so we don't know what they are. they can be anything.

``willReceive`` is not a good name for that feature, as the Prophecy convention is that any ``will*`` method is about the promise of the method (what the method will do when being called).
I don't like the name ``has`` either as it does not describe what the method does. However, I don't have a good naming idea right now

**Comment by hhilbert** [comment]
Yes, the biggest problem seems to find the right name for that method. What about `recognizes` or 'provides`?

**Comment by stof** [comment]
well, the following code does not read natural:

```php
$collection->provides('getItem', ['foo'])->willReturn($item);

$collection->recognizes('getItem', ['foo'])->willReturn($item);
```

We are not recognizing or providing anything here.

compare this to the flow when reading the API based on magic calls:

```php
$collection->getItem('foo')->willReturn($item);
```

the fact that we add a method name in the middle will clearly make it less readable in the flow, but we should still aim to be as readable as possible.

On a side note, this means that if you are doubling a class which uses the same method name than the one we will be choosing, you will not be able to use the magic API anymore for this method (which is already the case for other methods of the ObjectProphecy currently, which is another reason to have a non-magic API without having to use ``->__call('getItem', ['foo'])``). The fact that we add a new reserved method name means we will have to bump the major version of Prophecy to 2.0

**Comment by hhilbert** [comment]
Point taken. Thanks for your explanation.
