### ISSUE TITLE
Make expectation return different result based on call count

### ISSUE THREAD

**Issue by aik099** [phpspec/prophecy#213]
On a new project I'm trying out Prophecy to do the mocking instead of Mockery, that I've used before just to see how it works and such.

So far I was quite impressed by the fact, that the while describing how Mock should work I was able to spot inefficiencies in class, that was supposed to use the mock and refactor them.

The Mockery's feature I'm missing is for mock expectation to return different value based on call number, while each call has exactly same arguments.

For example:

```php
$mock->methodName('param1', 'param2')->willReturn(5); // on 1st call
$mock->methodName('param1', 'param2')->willReturn(6); // on 2nd call
$mock->methodName('param1', 'param2')->willReturn(6); // on other calls
```

Maybe this can somehow be done through this code, but I don't know yet how exactly:

```php
$mock->methodName('param1', 'param2')->will(function ($args, $mock) {
    $mock->methodName(...)->will...
});

```

**Comment by ciaranmcnulty** [comment]
You're on the right lines, there are two ways to do it:

Explicitly model the change:

```php
$mock->methodName('param1', 'param2')->will(function ($args, $mock) {
    $mock->methodName('param1', 'param2')->willReturn(6);
    return 5;
});
```

This method is useful for making it clear why the change is happening.

In other cases, e.g. modelling some sort of simple iteration where the different returns are just caused by sequencing, `willReturn` can take multiple parameters:

```php
$mock->methodName('param1', 'param2')->willReturn(5,6,6);
```

**Comment by stof** [comment]
I suggest you to read http://everzet.com/post/72910908762/conceptual-difference-between-mockery-and-prophecy

**Comment by aik099** [comment]
> `$mock->methodName('param1', 'param2')->willReturn(5,6,6);`

Thanks @ciaranmcnulty. The same way a Mockery does. I thought this was impossible because it wasn't documented. The good documentation is something, that Prophecy surely would benefit of since most of methods aren't even auto-completed by IDE and the only way to know how stuff works is digging through Prophecy code.

> I suggest you to read http://everzet.com/post/72910908762/conceptual-difference-between-mockery-and-prophecy

Thanks @stof . I read it previously a few times to transform my thinking way into Prophecy way of doing things.

**Comment by aik099** [comment]
@ciaranmcnulty I've looked at `will` method declaration at https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Prophecy/MethodProphecy.php#L137-L154 and it doesn't seem to accept multiple arguments.

One interesting think though is that `MethodProphecy` instance is given to the promise callback, when it's evaluated in https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Promise/CallbackPromise.php#L64 so theoretically it can be used to get call count up to this point of that expectation and made needed decision.

Than final code would look like this:

```php
$mock->methodName('param1', 'param2')->will(function ($args, $mock, $methodProphecy) {
    $methodCalls = $mock->findProphecyMethodCalls(
        $method->getMethodName(),
        new ArgumentsWildcard($args)
    );

    return $methodCalls === 0 ? 5 : 6;
});
```

The amount of code to make this happen is indeed huge, but I see no other way since `->will(...)` doesn't accept multiple arguments.

**Comment by aik099** [comment]
@ciaranmcnulty, my apologies. I've looked into `->will(` method, but `->willReturn(` will indeed work as  described - accept multiple arguments.

**Comment by bicpi** [comment]
@aik099 This PhpStorm plugin gives auto-completion for Prophecy (and more) in PHPUnit: https://github.com/maxfilatov/phpuaca There's no stable release yet, but it works pretty well for me since 2 months.
