### ISSUE TITLE
ExportUtil::recursiveExport Allowed memory size x bytes exhausted

### ISSUE THREAD

**Issue by jakari** [phpspec/prophecy#221]
I'm mocking an call on a prophecy that uses a doctrine object as parameter. like this: 

$prophecy = $this->prophesize(ClassToMock::class);
$prophecy->aMethodCall($doctrineEntity)->shouldBeCalledTimes(1);

Everything is fine until we make the checkPredictions check, and when the test fails (I havent made the required amount of calls to the prophecy) the expected output is printed to screen using ExportUtil, right? 
Now, a doctrine entity might be highly recursive, and when outputting it using print_r as exportUtil does, this results in a never ending loop and the php stalls to memory exhaust. 

I think there should be some more sophisticated way to print the output of the object. For example something on the style of doctrine/common Debug::dump?

**Comment by nick-jones** [comment]
This came up recently in phpspec/phpspec#785 too (the issue is here though, so I'm not suggesting this is a duplicate :) My suggestion over there was that phpspec/prophecy#121 may potentially resolve this.

**Comment by nick-jones** [comment]
I did a quick & dirty test -- having `ExportUtil` utilise an instance of `\SebastianBergmann\Exporter\Exporter` makes everything behave nicely. Unfortunately it's not as simple as that, due to the customisations mentioned over in phpspec/prophecy#121. Anyway, at least it seems like a viable way to fix this issue.

**Comment by jakari** [comment]
Oh I see. I must try to see if I'd have the time to make a PR out of this... It seems to be an issue that has been floating around too long. There must also be other users with this same issue. The issue itself is not that major but it causes a terrible headache since it degrades functionality a bit.
