### ISSUE TITLE
Return Type hint "self" causes error in PHP7

### ISSUE THREAD

**Issue by jschreuder** [phpspec/prophecy#240]
I'm experiencing this with Prophecy 1.5.0 when used in PhpSpec 2.3.0 or current dev-master.

When I prophesize a class with a method with this signature:

```php
<?php
    public function setRouter(Router $router) : self
```

It errors saying:

    PHP Fatal error:  '\self' is an invalid class name in vendor\phpspec\prophecy\src\Prophecy\Doubler\Generator\ClassCreator.php(49) : 
    eval()'d code on line 10

When I look into the generated code, it shows this signature:

```php
<?php
    public  function setRouter(\FastRoute\Dispatcher $router): \self
```

I looked into fixing it by adding an extra case to `Prophecy\Doubler\Generator\Node\MethodNode` in the `setReturnType()` method. But as far as I see the parent class isn't passed to the MethodNode, thus I can't replace `self` with the parent class's name. I'm not familiar enough with the codebase to be certain if just passing in the parent is a good fix, or if there's a better way to do this?

**Comment by Taluu** [comment]
Well, you could always during a ClassNode iterate through the MethodNodes and then here decide how to replace `\self` but this looks dirty.

I'm interested if a solution is found.

**Comment by kekko1212** [comment]
interested too
