### ISSUE TITLE
Scalar type declaration 'string' must be unqualified

### ISSUE THREAD

**Issue by radmen** [phpspec/prophecy#243]
When mocked class has methods with scalar type hints following error occurs:

> Fatal error: Scalar type declaration 'string' must be unqualified in /usr/src/app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 5

Error happened when this particular interface was mocked:

```php
<?php
interface UsersRepositoryInterface
{
    public function findByEmail(string $email);

    public function save(User $user): User;

    public function getById(string $id): User;
}
```

Yet I think it doesn't matter if it's a class or interface.

This error can be reproduced only on PHP >= 7.0.1

**Comment by stof** [comment]
Already fixed in the dev version by https://github.com/phpspec/prophecy/pull/235

**Comment by TomasVotruba** [comment]
Same issue, newer PHP version - 7.1:

```
Scalar type declaration 'void' must be unqualified in...
````
