### ISSUE TITLE
Cloning ObjectProphecy with all its predictions ? 

### ISSUE THREAD

**Issue by Bavragor** [phpspec/prophecy#248]
I think its not possible, at least I didn't found a way to do it.
Maybe implement this via a __clone function ? 

This would be really helpful e.g. for a dataProvider.

**Comment by aik099** [comment]
Why not to setup prediction right in test method using values supplied by data provider? Or you want data provider to supply test with ObjectProphercy objects instead?

**Comment by Bavragor** [comment]
Actually I supply ObjectProphecies via data provider for the test, but in the data provider I want to set some general predictions, clone the ObjectProphecy and then set some specific predictions for every dataset which will be supplied.

**Comment by aik099** [comment]
I've never done so myself. I only specify scalar values, like string/int/array via data provider and this way when something fails I see exact set from data provider that caused the failure. Not sure if in such case objects would be displayed correctly.

**Comment by aik099** [comment]
Also keep in mind, that while in data provider method you don't have access to whatever "setUp" method of the test has done, because it was never called yet.

**Comment by everzet** [comment]
Seems to be very specific and complex edge-case. I wouldn't complicate the Prophecy core for that, sorry.
