### ISSUE TITLE
PHP method names are case insensitive but Prophecy method names are not

### ISSUE THREAD

**Issue by chx** [phpspec/prophecy#249]
In `ObjectProphecy::getMethodProphecies` we have `if (!isset($this->methodProphecies[$methodName])) {` -- this probably needs a `strtolower`.

**Comment by aik099** [comment]
This if you set an expectation for `themethod` and method in a class is called `theMethod` it would never match and moreover would probably fail due exception that method doesn't exist on a mocked class?

**Comment by chx** [comment]
Just so. See http://stackoverflow.com/questions/34931201/php-prophecy-mystery

**Comment by aik099** [comment]
I with there was a flag in PHP that would make method names case sensitive.

**Comment by chx** [comment]
I run (or ran) the blog phpwtf.org , I also have a number of things I wish PHP were doing different. (Try `php -r '$a="";$a[0]="x";var_dump($a);')

**Comment by my2ter** [comment]
Duplicate of https://github.com/phpspec/prophecy/issues/165
