### ISSUE TITLE
Possibility to mock method chaining

### ISSUE THREAD

**Issue by andho** [phpspec/prophecy#25]
Moved from: https://github.com/phpspec/phpspec/issues/128

Is it posiible to mock a dependency that is used with method chaining?
I would like something like this:

``` php
function let($db) {
    $db->beAMockOf('DbConnection');
    $db->select('*')->from('table')->limit(20)->fetchAll()->willReturn(...);
    $this->beConstructedWith($db);
}

function it_should_load_data() {
    $this->getData()->shouldReturn(...);
}
```

**Comment by kirkbushell** [comment]
@everzet it's not breaking SRP if it's returning the same instance you're calling, right?

So if the chain is part of the same object, isn't the opinion incorrect in some cases?
