### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by Sam-Burns** [phpspec/prophecy#252]
Hi guys,

It's been six months since you put a release tag on this repo.  Given that critical bugs like https://github.com/phpspec/prophecy/issues/243 have been fixed since then, could you put a new release tag on the repository please?

Thanks for your help with this.

**Comment by jdreesen** [comment]
I would be happy about a release, too. Mostly because of #208.

**Comment by Sam-Burns** [comment]
@ciaranmcnulty any chance you could quickly stick a release tag on it for us?

**Comment by everzet** [comment]
Coming

**Comment by jdreesen** [comment]
Nice, thx! :)
