### ISSUE TITLE
I'm willing to help maintaining the repo

### ISSUE THREAD

**Issue by aik099** [phpspec/prophecy#254]
I'm willing to help maintaining the repo. Please add me as maintainers (the PR merge rights and release creation rights).

**Comment by yourwebmaker** [comment]
:+1:  PHPUnit now uses Prophecy as a mocking alternative and its use has increased a lot.

For a long time they don't release/merge anything. :cry:

**Comment by aik099** [comment]
@everzet , I have no idea who the maintainer of the library is, that can add new users to organization. Maybe it's you.

**Comment by everzet** [comment]
@aik099 I am back. But just added you as a maintainer in case I'm away again :)

**Comment by aik099** [comment]
Thanks.
