### ISSUE TITLE
Prophecy exceptions may never reach test results

### ISSUE THREAD

**Issue by vintage-dreamer** [phpspec/prophecy#267]
Prophecy does a really good job by early exposing design mistakes, but tracing caught problems can be a tricky thing. The example below (it works out-of-box) primitively imitates the problem I encountered and it took me quite a while to figure out what was the real problem.

I use _PHPUnit 4.8.24_, _Prophecy 1.4.1_.

```php
class SyncHandler {

	private $performer;

	public function __construct(ISyncPerformer $performer) {
		$this->performer = $performer;
	}

	public function sync() {
		try {
			// intentionally bad architecture of ISyncPerformer
			$this->performer->performSync($this->performer->createApiHandler());
		} catch (\RuntimeException $e) {
			// it will catch Prophecy's UnexpectedCallException
			echo "\n-=Hidden test result:=-\n" . $e->getMessage();
		}
	}

}

interface ISyncPerformer {
	public function performSync(MyApiHandler $apiHandler);
	public function createApiHandler();
}

/**
 *
 */
class BugTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @test
	 */
	public function sync() {
		$performer = $this->prophesize(ISyncPerformer::class);
		$performer->performSync(Prophecy\Argument::any())->shouldBeCalled();


		$handler = new SyncHandler($performer->reveal());
		$handler->sync();
	}

}
```

The output will be:

> Some predictions failed:
>   Double\ISyncPerformer\P1:
>     No calls have been made that match:
>       Double\ISyncPerformer\P1->performSync(*)
>     but expected at least one.
> 
> -=Hidden test result:=-
> Method call:
>   - createApiHandler()
> on Double\ISyncPerformer\P1 was not expected, expected calls were:
>   - performSync(*)

So the test result tells us: 
> No calls have been made that match: Double\ISyncPerformer\P1->performSync(*)

It's true indeed, but the reason for that is a different exception thrown by Prophecy itself (that exposes another problem with the test or code) and not logged in the test runner. I expected Prophecy to print both errors. It makes tracing harder. It may even lead to situations when test runs green, because an exception is suppressed.

So why aren't Prophecy exceptions logged somehow and can be suppressed by implementation being tested?

Again, it's not about design or lacking of features to test bad code. Prophecy did a great job, but it cost me time to find the real reason, which it actually detected, but just didn't show me. And I don't see a workaround for this. Am I wrong?

**Comment by stof** [comment]
Prophecy cannot deal with the output, because it has no idea about how the output is expected to loo like (it does not know what is using the library).

To me, the issue is in your architecture. Catching exceptions silently is what cause debugging pain.

**Comment by vintage-dreamer** [comment]
> Catching exceptions silently is what cause debugging pain.

Why silently? It's a level of the app that's competent to log exceptions and continue with a next API action. If the logger is a service, one can easily mock it or read from it, so the behavior is testable. I don't really see a design problem here. But even if so, this particular example of Prophecy's behavior doesn't seem educating.

> Prophecy cannot deal with the output, because it has no idea about how the output is expected to loo like

Ok, but is there anywhere a stack of Prophecy's exceptions? If Prophecy just throws an exception while running its mocks on user's code, what kind of library could access it?

**Comment by everzet** [comment]
As @stof said - you have architecture issue. You're catching all exceptions independent of where they came from. That's a bad practice in general particularly because you inevitably get yourself in situations like this one, where you suppress exceptions that shouldn't be suppressed (in testing or not). Better approach would be to use and catch more specific custom exceptions instead of blanket approach you adopted.

In regards to Prophecy architecture itself, the only change around your problem would be to delay throwing of all double-related exceptions until the `Prophect::checkPredictions()` call. We can not do that, because doing so will get your tests even more complicated and convoluted - if the call to double wasn't been predicted, I wouldn't expect test to continue routine as nothing happened - I'd expect test to stop immediately, which is what exceptions currently achieve.

**Comment by vintage-dreamer** [comment]
Thanks for the interesting reply, @everzet ! But pls let me object.

1. There can be situations when exceptions are unpredictable, but fallback actions are required. And that's the case of the example. But I agree that handling unpredictable exceptions together with expected ones is not the responsibility of `SyncHandler` and it should be lifted one level more. But again, it's a delicate design problem, a testing framework should not tangle more. Especially when it helps so much with other kinds of design problems.

2. Prophecy could handle it better and still remaining independent of PHPUnit.
PHPUnit can also be tricked exactly like Prophecy when its exception is caught and suppressed in an app. But unlike Prophecy it would print an error message anyway. This is _expected behavior_. So when a test case method finishes PHPUnit still continues its job in `\PHPUnit_Framework_TestCase::runBare()` and calls e.g. `\PHPUnit_Framework_TestCase::verifyMockObjects()` where it checks stacks of errors and throws an exception again if it hasn't been done. At this point it could also poll somehow Prophecy's stack of error messages, but there isn't one. Let's maybe introduce it?

**Comment by stof** [comment]
@vintage-dreamer ``Prophect::checkPredictions`` is called inside ``\PHPUnit_Framework_TestCase::verifyMockObjects()``. But unexpected calls are not something checked by ``Prophect::checkPredictions``
