### ISSUE TITLE
A promise that allows to throw an exception first and then return a value when called another time

### ISSUE THREAD

**Issue by pamil** [phpspec/prophecy#270]
Let's say I have a collaborator, which should throw an exception if called first time and return a value if called another time.

```php
$collaborator->shouldThrow(\Exception::class)->during('method');
$collaborator->method()->shouldReturn('value');
```

I've implemented a [CompositePromise](https://github.com/pamil/prophecy-common/blob/master/src/Promise/CompositePromise.php) which allows it, is it something that we would like in Prophecy itself?

**Comment by aik099** [comment]
What the use case of that could be?

**Comment by stof** [comment]
The philosophy of Prophecy is that calling the method twice with the same input should yield the same behavior. This is why something like CompositePromise is not in core

**Comment by pamil** [comment]
The use case I've come into was specifying caching decorator of a service. The service could return an  object or could throw an exception, that there is no object, depending of its state. Then caching decorator  was caching the output (exception / returned value), but it should not cache anything when some special conditions were fulfilled (no master request here) - then it should return the same values as cached service every time (and here comes the CompositePromise).

Anyway, that's quite complicated edge case and I see the point of not allowing using it so easily. Thanks for explanation! :)

**Comment by mikedfunk** [comment]
For those arriving here via google, it seems this limitation no longer exists. E.g.

```php
        $callCount = 0;
        $takeAction = function () use (&$callCount) {
            // return something the second time
            if ($callCount === 1) {
                return 'thing';
            }
            // throw an exception the first time
            $callCount++;
            throw new \Exception("thing not found");
        };

        $collaborator->getThing(123)->will($takeAction);
```
