### ISSUE TITLE
[symfony 3.1.x compatibility] Use phpdocumentor/reflection-docblock 3.0

### ISSUE THREAD

**Issue by karser** [phpspec/prophecy#272]
Hello, I encountered with a conflict that will eventually prevent users to update to Symfony 3.1
composer output:
```
phpunit/phpunit 5.* requires phpspec/prophecy, 
phpspec/prophecy requires phpdocumentor/reflection-docblock ~2.0
​phpdocumentor/reflection-docblock ~2.0  conflicts with symfony 3.1*​
```
phpdocumentor/reflection-docblock already has 3.0 stable version https://github.com/phpDocumentor/ReflectionDocBlock/issues/70

Please see conflict section https://packagist.org/packages/symfony/symfony#3.1.x-dev

**Comment by aik099** [comment]
Thanks for noticing. Would you please send a PR that would allow usage of `2.0` or `3.0` version of `​phpdocumentor/reflection-docblock`?

**Comment by GrahamCampbell** [comment]
> that would allow usage of 2.0 or 3.0 version of ​phpdocumentor/reflection-docblock?

:+1:

**Comment by tacman** [comment]
Symfony 3.1RC1 was released today.  Any progress on this conflict?

**Comment by theofidry** [comment]
See #264 and #273. There's some work started there but that could not be finished due to lack of time.

**Comment by hiddewie** [comment]
Symfony 3.1 was just released. Is there any progress here, because this issue prevents an upgrade of Symfony when using PHPUnit?

**Comment by dunglas** [comment]
See https://github.com/phpspec/prophecy/pull/275

**Comment by luispabon** [comment]
Will the aforementioned fix make it to 3.1.1?

**Comment by stof** [comment]
@luispabon which 3.1 version are you talking about ?

**Comment by dunglas** [comment]
@luispabon this isn't a problem in Symfony. It's a problem in Prophecy (because of a bug in `reflection-docblock`). See #275.

**Comment by theofidry** [comment]
@luispabon as the problem doesn't come from Symfony, Symfony doesn't need a new release, only `reflection-docblock` does :)

**Comment by stof** [comment]
@theofidry and Prophecy as well, with the support of reflection-docblock 3.x being merged

**Comment by theofidry** [comment]
true

**Comment by Hast** [comment]
@stof any news here?

**Comment by theofidry** [comment]
From https://github.com/phpspec/prophecy/pull/275#issuecomment-223927782:

>I will do a release this evening

**Comment by stof** [comment]
1.6.1 has been released
