### ISSUE TITLE
willThrow does not support throwing Errors on PHP7

### ISSUE THREAD

**Issue by khelle** [phpspec/prophecy#281]
As the title say, ther is no possibility to mock throwing Errors in PHP7 using prophecy.

```
$prophecyMethod->willThrow(new Error());
```

This should be possible but is not.

**Comment by GrahamCampbell** [comment]
Looks like this code needs to change: https://github.com/phpspec/prophecy/blob/7ca4182b3acbd19ebbf3ced4dfee12487d9c05aa/src/Prophecy/Promise/ThrowPromise.php#L41-L60.

**Comment by khelle** [comment]
I have already checked this before, but adding Error support in this fragment of code does not fix the problem. Instead of compilation errors I start to get predictions errors:

```
Some predictions failed:
   //...
    Expected exactly 1 calls that match:
      //...
    but none were made.
```

It seems there need to be additional internal changes done aside from quoted fragment of code.

**Comment by GrahamCampbell** [comment]
Hmmm, sad times. I guess there's more places that need changing then?
