### ISSUE TITLE
Planed version with support for phpspec 3.0.0 ?

### ISSUE THREAD

**Issue by remicollet** [phpspec/prophecy#282]
phpspec 3.0.0 requires prophecy ^1.5

but latest prophecy 1.6.1 requires (for dev) phpspec ^2.0, and indeed test suit fails.

**Comment by guiwoda** [comment]
@remicollet Requiring `phpspec/phpspec:^3.0` will bring prophecy 1.6.1.

**Comment by stof** [comment]
@remicollet the prophecy testsuite has not yet been migrated to phpspec 3 (they removed the phpdoc-based definition of collaborators).

But this does not change anything for users of the library. Prophecy does not ever depend on phpspec at runtime. It uses phpspec 2 as a development tool only.
Migrating our testsuite to phpspec 3 is a low priority task for me (it is a boring task too), but I will gladly accept any help (the first step is to migrate collaborators to be defined with typehints, while still using phpspec 2)

**Comment by ciaranmcnulty** [comment]
If you did switch to PhpSpec 3.x you would not be able to test against PHP versions < 5.6.0, so it would probably need to wait until the next major Prophecy version

**Comment by jameshalsall** [comment]
@stof I've made a start on this, see #289
