### ISSUE TITLE
SplObjectStorage unwrapping issue

### ISSUE THREAD

**Issue by stingus** [phpspec/prophecy#283]
Having 3 classes:

    class Baz
    {
         private $payload;

         public function getPayload()
         {
            return $this->payload;
         }
    }

    class Foo
    {
         private $baz;
         private $bazCollection;

         public function getBaz()
         {
             return $this->baz;
         }

         public function getBazCollection()
         {
             return $this->bazCollection;
         }
     }

    class Bar
    {
        private $foo;

        public function __construct(Foo $foo)
        {
            $this->foo = $foo;
        }

        public function getBaz()
        {
            $data = $this->foo->getBaz();
            if ($data->getPayload() != 1) {
                throw new \Exception('Wrong payload');
            }
        }

        public function getBazCollection()
        {
            $data = $this->foo->getBazCollection();
            $data->rewind();
            for ($i = 1; $i <= 3; $i++) {
                $baz = $data->current();
                $payload = $baz->getPayload();
                if ($payload != $i) {
                    throw new \Exception('Wrong payload on collection');
                }
                $data->next();
            }
        }
    }

I want to run some examples on Bar, so here's my BarSpec file:

    class BarSpec extends ObjectBehavior
    {
        function it_has_baz_collection(Foo $foo)
        {
            $prophet = new Prophet();
            $storage = new \SplObjectStorage();
            $baz1 = $prophet->prophesize('Baz');
            $baz1->getPayload()->willReturn(1);
            $baz2 = $prophet->prophesize('Baz');
            $baz2->getPayload()->willReturn(2);
            $baz3 = $prophet->prophesize('Baz');
            $baz3->getPayload()->willReturn(3);
            $storage->attach($baz1);
            $storage->attach($baz2);
            $storage->attach($baz3);
            $foo->getBazCollection()->willReturn($storage);
            $this->beConstructedWith($foo);
            $this->getBazCollection();
        }

        function it_has_baz(Foo $foo)
        {
            $prophet = new Prophet();
            $baz = $prophet->prophesize('Baz');
            $baz->getPayload()->willReturn(1);
            $foo->getBaz()->willReturn($baz);
            $this->beConstructedWith($foo);
            $this->getBaz();
        }
    }

I need to set a mock (Baz or Baz collection) on another mock (Foo), the last one being used on Bar.

The example `it_has_baz_collection` will fail with `notice: Object of class Prophecy\Prophecy\MethodProphecy could not be converted to int` because it seems that unwrapping objects in SplObjectStorage does not work. I don't know if it's related to #26. 
Example `it_has_bazz` works, replicating the same conditions, but without using the SPL storage. Can anybody confirm this case and suggest a workaround maybe (except ditching the SPL :)) ?

**Comment by stof** [comment]
Why are you using your own Prophet in your spec ? phpspec already handles prophecy for you.

The issue in your case is that you attach the ObjectProphecy to the SplObjectStorage, not the mock itself. You need to call ``->reveal()`` and attach its return value instead.
Working with the ObjectProphecy is possible only as long as you stay in the Prophecy domain (which will handle revealing when needed). As soon as you want to pass the mock to other objects, you must reveal it before, to get the actual mock.

**Comment by stingus** [comment]
The Prophet instance was left from a real-world case, where the mock is not created in the example method, but in a private method. As far as I know (and tested) you cannot create a stub in a method that is not an example (it_* its_* methods), other than using a new Prophet instance. Is there another way to create stubs except using the argument hinting or beADoubleOf() method?

I tested with reveal() and it works, thank you! I don't honestly understand why it works with a simple object (it_has_baz), without reveal().

**Comment by stof** [comment]
In ``it_has_baz``, you never pass the ObjectProphecy to a class outside the Prophecy domain. You only pass your ``$baz`` variable to another Prophecy object, which knows how to handle the case where it receives an ObjectProphecy rather than the actual double.

**Comment by stingus** [comment]
thanks @stof!
