### ISSUE TITLE
PHP 7.1 nullable arguments throws ParseError

### ISSUE THREAD

**Issue by danizord** [phpspec/prophecy#286]
In PHP 7.1 (RC 1), the `ReflectionParameter::getType()` method returns the type with a leading `?` when the default value is null: https://3v4l.org/MERq5

So, when prophesizing a class which contains scalar typehint with default vale as null, the argument typehint is falling [here](https://github.com/phpspec/prophecy/blob/588bdd96556ecfdba4beceda6629e89b13d12654/src/Prophecy/Doubler/Generator/ClassCodeGenerator.php#L92-L96), and `ClassCodeGenerator` is adding a leading backslash to the typehint, which becomes `\?string`.

That makes the `ClassCreator` throw a `ParseError` when parsing the class code [here](https://github.com/phpspec/prophecy/blob/588bdd96556ecfdba4beceda6629e89b13d12654/src/Prophecy/Doubler/Generator/ClassCreator.php#L49):

>ParseError: syntax error, unexpected '?', expecting identifier (T_STRING)

How should we proceed to fix this issue?

**Comment by ciaranmcnulty** [comment]
I've opened a PHP bug https://bugs.php.net/bug.php?id=73105 - we should see what the response there is first.

**Comment by ciaranmcnulty** [comment]
Although this still needs fixing for when people actually do use nullable types

**Comment by stof** [comment]
The first step to fix it will be to merge https://github.com/phpspec/prophecy/pull/274, i.e. stop mocking the Reflection API

**Comment by stof** [comment]
I hope the PHP team will accept https://github.com/php/php-src/pull/2136 which fixes the BC break

**Comment by ciaranmcnulty** [comment]
Looks like https://github.com/php/php-src/pull/2137 got merged 🎉

**Comment by danizord** [comment]
Nice! I'll check it again as soon as they release the next PHP 7.1 RC Docker image :)

**Comment by ciaranmcnulty** [comment]
Yep this is fixed in PHP:

```php
class Foo
{
    function bar(string $foo = null){}
}

$prophet = new Prophecy\Prophet();
$prophecy = $prophet->prophesize(Foo::class);
$double = $prophecy->reveal();

echo get_class($double), "\n";
```

7.1.0-RC2 output:
```
PHP Parse error:  syntax error, unexpected '?', expecting identifier (T_STRING) in /Users/cmcnulty/Documents/Kata/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 5
```

7.1.0-RC3 output:
```
Double\Foo\P1
```

**Comment by ciaranmcnulty** [comment]
Thanks for raising this @danizord, it gave an opportunity to highlight the problems back to php-internals
