### ISSUE TITLE
Prophecy needs to be updated to use/require sebastian/recursion-context 2.0

### ISSUE THREAD

**Issue by sebastianbergmann** [phpspec/prophecy#296]
Prophecy currently requires `"sebastian/recursion-context": "^1.0"`. This means that installing PHPUnit will install an outdated version of Prophecy, one which does not require recursion-context.

When I bump the required version of Prophecy in PHPUnit 5.6's `composer.json` then I get this:

```
- Installation request for phpspec/prophecy ^1.6.1 -> satisfiable by phpspec/prophecy[v1.6.1].
- phpspec/prophecy v1.6.1 requires sebastian/recursion-context ^1.0 -> satisfiable by sebastian/recursion-context[1.0.0, 1.0.1, 1.0.2].
- Can only install one of: sebastian/recursion-context[2.0.0, 1.0.0].
- Can only install one of: sebastian/recursion-context[2.0.0, 1.0.1].
- Can only install one of: sebastian/recursion-context[2.0.0, 1.0.2].
- sebastian/exporter 2.0.0 requires sebastian/recursion-context ~2.0 -> satisfiable by sebastian/recursion-context[2.0.0].
- Installation request for sebastian/exporter ~2.0 -> satisfiable by sebastian/exporter[2.0.0].
```

This is blocking the release of PHPUnit 5.6.5.

**Comment by sebastianbergmann** [comment]
You basically need the equivalent of https://github.com/sebastianbergmann/exporter/commit/ecbefe18c83d6d04a0d4e4d0881efd055533a07d

**Comment by sebastianbergmann** [comment]
BTW: I would like to know why you are duplicating code from https://github.com/sebastianbergmann/exporter. Would be great if we could adapt Exporter to suit your needs thus eliminating the need for duplication.

**Comment by stof** [comment]
@sebastianbergmann AFAIK, the only difference is that we have a special dumping for Prophecy objects to avoid dumping the internals of the mock. But it would be great to move it to the exporter directly (which would also benefit the dumping done by PHPUnit btw)

**Comment by sebastianbergmann** [comment]
A pull request would be welcome then :-) Either that or opening a ticket that explains what you need (probably optional blacklisting).

**Comment by stof** [comment]
See https://github.com/phpspec/prophecy/blob/5c324f4951aca87a2de61b7903b75126516b6386/src/Prophecy/Util/ExportUtil.php#L184
We don't display the internal of the Prophecy object (which will itself be inside the mock when dumping it), to make the object dumping shorter (especially given that the ObjectProphecy contains a circular object graph)

**Comment by sebastianbergmann** [comment]
Thanks for the ticket. Any estimate on when this issue will be resolved? Thanks!

**Comment by stof** [comment]
@sebastianbergmann as soon as you update your PR to allow both versions (and then the time to tag a release, which can be done right after it)

**Comment by sebastianbergmann** [comment]
I had to sent a new pull request (was not able to update the existing one), sorry for that.

**Comment by stof** [comment]
And here you go. A fresh new 1.6.2 release containing your fix.

**Comment by sebastianbergmann** [comment]
Thanks a lot!
