### ISSUE TITLE
Nullable return method "must be an instance of {class name}, null returned"

### ISSUE THREAD

**Issue by elegos** [phpspec/prophecy#303]
PHP 7.1.0 (release)
PHPUnit 5.7.2
Prophecy 1.6.2

Hello!

With the new PHP 7.1.0 released some days ago, PHP introduced the nullable return. I've tried mocking one of these methods, but apparently Prophecy does not support them yet (PHPUnit with `PHPUnit_Framework_MockObject_MockObject` does, so it's not PHPUnit).

May you please take a look at it?

This is a minimal test which reproduces the error:

    <?php
    
    class Nullable {
        public function getNullable() : ?Nullable {
            return null;
        }
    }
    
    class BaseProphecyFailTest extends PHPUnit_Framework_TestCase
    {
        public function testNullable()
        {
            /** @var Nullable|\Prophecy\Prophecy\ObjectProphecy $mock */
            $mock = $this->prophesize(Nullable::class);
            $mock->getNullable()->willReturn(null);
    
            $mock = $mock->reveal();
    
            $this->assertNull($mock->getNullable());
        }
    }

Output:

    Testing started at 09:50 ...
    PHPUnit 5.7.2 by Sebastian Bergmann and contributors.

    Return value of Double\Nullable\P1::getNullable() must be an instance of Nullable, null returned
     BaseProphecyFailTest.php:19

    Time: 121 ms, Memory: 4.00MB

    ERRORS!
    Tests: 1, Assertions: 0, Errors: 1.
    
    Process finished with exit code 2

**Comment by deeky666** [comment]
I think this is fixed by #322 and can be closed.
