### ISSUE TITLE
Asserting Value Objects

### ISSUE THREAD

**Issue by dgafka** [phpspec/prophecy#307]
There is not efficient way for comparing value objects, so the internal state of the object doesn't need to be exposed.

Let's take simple example under consideration:
     
     class Number
     {
         /**
          * @var int
          */
         private $amount;
     
         /**
          * Number constructor.
          * @param int $amount
          */
         public function __construct(int $amount)
         {
             $this->amount = $amount;
         }
     }

In `phpspec` I can't validate the amount without exposing internal state. Because something like this doesn't work `$this->shouldBe(new Number(5))`. So only work around for this is to go with public interface `equals`.

     class NumberSpec extends ObjectBehavior
     {
         function let()
         {
             $this->beConstructedWith(5);
         }
     
         function it_is_initializable()
         {
             $this->shouldHaveType(Number::class);
         }
     
         function it_should_be_equal_to_five()
         {
             $this->equals(new Number(5))->shouldReturn(true);
             $this->equals(new Number(10))->shouldReturn(false);
         }
     }

This looks like fine public API, but problem arrives when some of your other class return array of 
`Numbers`. 

Now let's extend our implementation to return array of numbers from passed starting point to the ending point.

    /**
     * @param int $startAt
     * @param int $endAt
     * @return array|Number[]
     */
    public function createInRange(int $startAt, int $endAt) : array
    {
        $numbersInRange = [];

        for ($currentNumber = $startAt; $currentNumber <= $endAt; $currentNumber++) {
            $numbersInRange[] = new Number($currentNumber);
        }

        return $numbersInRange;
    }

Let's skip the part that this method is really dumb and would rather be static. 
There is no way to assert it in `phpspec`, without creating custom matchers 
Below example simply doesn't work.

      $this->createInRange(1, 3)->shouldReturn([new Number(1), new Number(2), new Number(3)]);

In `PHPUnit` it would be simple. 

     PHPUnit_Framework_Assert::assertEquals(
        $this->createInRange(1, 3), 
        [new Number(1), new Number(2), new Number(3)]
    );

`Proposal`: 
As value objects should be compared by properties, there should be some interface in phpspec, that will simply compare objects by values not by references.

    $this->createInRange(1, 3)->shouldBeExact([new Number(1), new Number(2), new Number(3)])

**Comment by ciaranmcnulty** [comment]
Can you open this issue in the phpspec/phpspec repository please? It's not really about Prophecy

**Comment by dgafka** [comment]
Done https://github.com/phpspec/phpspec/issues/1046.
