### ISSUE TITLE
Upstream BC break in sebastian/comparator (SebastianBergmann\Comparator\Comparator)

### ISSUE THREAD

**Issue by GawainLynch** [phpspec/prophecy#312]
`sebastian/comparator` v1.2.3 changes the abstract function signature, resulting in:

```
PHP Fatal error:  
Declaration of Prophecy\Comparator\ClosureComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) 
must be compatible with SebastianBergmann\Comparator\Comparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) 
in vendor/phpspec/prophecy/src/Prophecy/Comparator/ClosureComparator.php on line 42
```

Wasn't sure if you'd prefer to take this up with Sebastian directly, or hotfix Prophecy, so went for an issue rather than a PR.

**Comment by GawainLynch** [comment]
Never mind, Sebastian just tagged 1.2.4 that looks to have reverted this.

**Comment by ciaranmcnulty** [comment]
I guess we could blacklist 1.2.3 in the composer.json?

**Comment by GawainLynch** [comment]
That was the planned fallback, but given there was only a couple of hours between tagged versions it is a non-issue for us now.
