### ISSUE TITLE
Scalar type declaration 'void' must be unqualified

### ISSUE THREAD

**Issue by TomasVotruba** [phpspec/prophecy#314]
> Scalar type declaration 'void' must be unqualified in...

Same as: https://github.com/phpspec/prophecy/issues/243, just for newer PHP 7.1

**Comment by temp** [comment]
Just stumbled over this. Guess it's not as easy as in #243 as this problem sneaks through several classes...
MethodName::setReturnType() is missing handling the void return type, but this is not sufficient. It will still run in an error, as for example the ProphecySubjectPath always uses a returned statement. Code like this is generated:
```php
public  function removeBudget(\Budget $budget): void {
  return $this->getProphecy()->makeProphecyMethodCall(__FUNCTION__, func_get_args());
}
```
which results in
```
PHP Fatal error:  A void function must not return a value in ...
```

I'm not too deep in prophecy so I can't give any more insights in how to solve this.

**Comment by ENM1989** [comment]
Could this implementation from @thomasvargiu help?
https://github.com/thomasvargiu/prophecy/commit/ab39409d17d5b9c214d7eb30d065d45373b3024a

**Comment by temp** [comment]
@ENM1989 @thomasvargiu Yes, just tried it with his feature/php71-types branch, and it works like a charm!

**Comment by ENM1989** [comment]
@temp yeah.
@thomasvargiu is this branch ready to be merged?

**Comment by stof** [comment]
Closing as 1.7 has been released with proper support for this
