### ISSUE TITLE
How to allow call to original method?

### ISSUE THREAD

**Issue by loren-osborn** [phpspec/prophecy#332]
I suspect that I'm running into this issue as I'm trying to mix a wrapper that should probably be injected into the class that's using it, but I distinctly remember mocking some methods and not others in PHPUnit's mocking system some years ago, and would like to know how to do this in Prophecy.

In this situation, I have a class with four methods:

- Two methods simply wrap native PHP functions and definitely need to be mocked.
  - In this particular case I'm confident that I've been able to test that these methods do map correctly to the intended functions, though I can think of many similar situations where this wouldn't be the case.
- One is totally stateless, and simply transforms its input, so I can test it fully without any mocking. Given that I control its input, I'm happy to mock or not mock this method, Whatever is most convenient.
- The last method is the one I am trying to write tests for. It calls the other three methods. 

How do I write tests for the last method, with the first two or three methods mocked. I tried using `$objProph->methodToTest('argValue')->shouldBeCalled();`, but the `reveal()`ed object's method always returned `NULL` and I suspect never called the parent class method.

I am aware that I can simply put the first two methods in their own class (and perhaps I should do that) and pass this object to the original class's constructor. Then I could easily mock the injected object without worrying about mocking for the other two methods, but this seems a bit cumbersome. 

Is there currently a way in Prophecy to mock some methods and not others in a class? I thought these hybridized object classes were called "test doubles" but I may have my terminology wrong.

Please advise, Thanks.

**Comment by loren-osborn** [comment]
It may be helpful to add something about this a bit more explicitly to the documentation. Perhaps define and describe partial mocks, and why they're unsupported. This may save users like me hours picking through the code trying to untangle how to make prophecy spit out a partial double.

Based on my description, does the injected wrapper sound like a reasonable design? I generally avoid adding code paths in production code exclusively used by test code, but unless I force the production caller to always inject the wrapper object, (or forcing them to use DI container) injecting the wrapper class at run time will only be used by test code. Normally, I'd override the accessor to the wrapper object  with the mocked object in a partial double. What do you recommend as an alternative?

**Comment by loren-osborn** [comment]
(I suppose I could simply make the wrapper object property public, and set it to the mock in my test code)

**Comment by stof** [comment]
you can make the wrapper an *optional* constructor argument (instantiating one automatically in the constructor if not provided)

**Comment by loren-osborn** [comment]
Yes, but that still makes not constructing it when provided a testing-specific code path. :-(

**Comment by danepowell** [comment]
I just ran into the same issue, and while I suspected that the ultimate solution was to rearchitect the affected class, I would have really appreciated seeing this called out in the docs.
