### ISSUE TITLE
Question about multiple will on same method

### ISSUE THREAD

**Issue by sylouuu** [phpspec/prophecy#343]
Hi,

Got a question about the syntax to make multiple `will()` for the same method.

```php
// 1st call
$stripeCouponService->getOne($coupon->code)->willThrow(new InvalidRequest('No such coupon: ' . $coupon->code, 'Coupon'));

// 2nd call
$stripeCouponService->getOne($coupon->code)->willReturn($stripeCoupon);
```

I tried this as given in #213 

```php
$stripeCouponService->getOne($coupon->code)->will(function ($stripeCouponService) use ($coupon, $stripeCoupon) {
    $stripeCouponService->getOne($coupon->code)->willTrow(new InvalidRequest('No such coupon: ' . $coupon->code, 'Coupon'));
    $stripeCouponService->getOne($coupon->code)->willReturn($stripeCoupon);
});
```

Anyone to help me about the syntax to use?

Best

**Comment by damienflament** [comment]
Prophecy does not support it out of the box. As said [here](https://github.com/phpspec/prophecy#method-prophecies-idempotency):

> Prophecy enforces same method prophecies and, as a consequence, same promises and predictions
> for the same method calls with the same arguments.

The solution given in #213 is hacky in my opinion. It works, but it is not elegant.

In fact, your stub object should not return different values based on call order, but only on argument value.

Why your service should not find the requested coupon on first call, but should find it on second call ?

**Comment by sylouuu** [comment]
Actually I want to detect if the given coupon already exists before creating it. So if the service throws an exception (404 not found) I know that I can create it. Then I retrieve it another time to get the resource.

Best

**Comment by damienflament** [comment]
OK. So you're needs are not related to #213.

You should read [this section of the documentation](https://github.com/phpspec/prophecy#arguments-wildcarding).

The right way to do it might be:

```php
use Prophecy\Argument;

$stripeCouponService->getOne($coupon->code)
    ->willThrow(new InvalidRequest('No such coupon: ' . $coupon->code, 'Coupon'));

$stripeCouponService->setOne($coupon->code, $coupon)
    ->will(function($args) {
        list($code, $coupon) = $args;

        $this->getOne($code)->willReturn($coupon);
    });
}
```

Or, better:
```php
use Prophecy\Argument;

// The service does not have any coupon initially
$stripeCouponService->getOne(Argument::type('string'))
    ->willThrow(new InvalidRequest('No such coupon: ' . $coupon->code, 'Coupon'));

// The service will return a coupon if it was added
$stripeCouponService->setOne(Argument::type(Coupon::class))
    ->will(function($args) {
        list($coupon) = $args;

        $this->addOne($coupon->code)->willReturn($coupon);
    });
}
```

This way, your coupon service is correctly stubed regardless the value of the arguments.

**Comment by sylouuu** [comment]
I refactored because my design was not optimal. Now I avoid to do multiple `get` by catching exception on `create`. So I don't need to do that anymore.

Sure I'll try your proposal if I encounter the same issue. Thanks for your time.

Best
