### ISSUE TITLE
Unable to mock methods named 'declare', 'new', …

### ISSUE THREAD

**Issue by olvlvl** [phpspec/prophecy#351]
Reserved word restrictions have been loosened since PHP 7.0, one can name a method `declare`, `new`, or `private`:

http://php.net/manual/en/migration70.other-changes.php#migration70.other-changes.loosening-reserved-words

But mocking such methods is currently failing with Prophecy. Please consider the following code:

```php
class A
{
    public function declare()
    {
        echo "you should not see this";
    }
}

class ATest extends \PHPUnit\Framework\TestCase
{
    public function testA()
    {
        $a = $this->prophesize(A::class);
        $a->declare()
            ->shouldBeCalled()->willThrow(new \Exception);
        $a->reveal()->declare();
     }
}
```

One would except an exception to be thrown, alas "you should not see this" is printed instead. Mocking it failing with `new` or `private` too.

No problem mocking the method with PHPUnit:

```php
$a = $this->getMockBuilder(A::class)
    ->setMethods([ 'declare' ])
    ->getMock();
$a->method('declare')
    ->willThrowException(new \Exception);
$a->declare();
```

**Comment by olvlvl** [comment]
Oh, I found this: https://github.com/phpspec/prophecy/pull/337

Can't wait for the release!

**Comment by ciaranmcnulty** [comment]
Does #344 fix this?

**Comment by olvlvl** [comment]
It's working with master:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$prophet = new Prophecy\Prophet;

class A
{
    public function declare()
    {
        echo "you should not see this";
    }
}

$a = $prophet->prophesize(A::class);
$a->declare()->shouldBeCalled()->willThrow(new \Exception);
$a->reveal()->declare();
```
