### ISSUE TITLE
PHP 7.2 object type-hint

### ISSUE THREAD

**Issue by jansvoboda11** [phpspec/prophecy#355]
Hi all,

I was working with Prophecy on PHP 7.2 and I noticed that `object` typehints aren't handled properly yet.
`ClassCodeGenerator` currently generates code with namespaced `\object` typehint instead.

I don't think this will be hard to fix.

**Comment by dlakomski** [comment]
+1 for this

**Comment by olvlvl** [comment]
I'm working on a fix over here: https://github.com/olvlvl/prophecy/tree/olvlvl-type-object but other tests need fixing because they are failing on PHP 7.2: https://twitter.com/olvlvl/status/959388600642269184

**Comment by Majkl578** [comment]
Any progress? PHP 7.2 has been stable for almost 3 months now. This becomes a blocker for Doctrine. :/
