### ISSUE TITLE
"shouldHaveBeenCalled" doesn't work anymore

### ISSUE THREAD

**Issue by damien-carcel** [phpspec/prophecy#358]
Hello.

The pull request https://github.com/phpspec/prophecy/pull/341 introduced a problem with `MethodProphecy::shouldHave()`.

As the new calls are not recorded anymore in `CallCenter::recordedCalls` [here](https://github.com/phpspec/prophecy/commit/1e7f7a4d6231783af5cc3cac896ccd13617e41d2#diff-265a65814cf5eb345ef20e1f5c376dbfR118) during `CallCenter::makeCall()`, there is nothing to merge anymore in `MethodProphecy::calls` [here](https://github.com/phpspec/prophecy/commit/1e7f7a4d6231783af5cc3cac896ccd13617e41d2#diff-f738156de4f6ab0866acc96c728538c4R309), so "shouldHaveBeenCalled" prediction fails.

Here is an example of failing test in our application: https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/spec/Form/Type/FamilyTypeSpec.php#L41 .
We are using phpspec/phpspec 3.0.0 with phpspec/prophecy 1.7.1.

If I force in composer.json the use of phpspec/prophecy 1.7.0, the test is OK.

Regards,
Damien

**Comment by stof** [comment]
@everzet can you check this, as you approved #341 ?

**Comment by Mvannes** [comment]
+1.

Also seeing any case where a ```->shouldBeCalled()``` is used multiple times on the same signature when using ```Argument::that()```  fail.
Same for ```->shouldHaveBeenCalled()``` functions when the same signature was previously declared to return something using ```->willReturn()```. This pull request seems to have changed a lot of behaviour. 
Will create a proper issue for this if you want.

**Comment by everzet** [comment]
Reverted

**Comment by damien-carcel** [comment]
@everzet and @stof Thank you so much for your reactivity.
1.7.2 works for us, so I'm closing this issue.
