### ISSUE TITLE
Breaking PHP 5.6 Support in Older Versions of PHPUnit

### ISSUE THREAD

**Issue by astorm** [phpspec/prophecy#375]
Hello maintainers of a great free/open source tool!  I *think* some recent changes you've made to this repository have unexpectedly broken older version of PHPUnit that have `phpspec/prophecy` as a dependency.   I ran into this on the PHP 5.6 jobs for the travis build on one of my projects.  

Here's a build that [worked 15 days ago](https://travis-ci.org/astorm/pestle/jobs/300627637).

And here's [the build that broke](https://travis-ci.org/astorm/pestle/jobs/307345170), with the error message

      Problem 1
        - Installation request for phpdocumentor/reflection-docblock 4.1.1 -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].
        - phpdocumentor/reflection-docblock 4.1.1 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
      Problem 2
        - phpdocumentor/reflection-docblock 4.1.1 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
        - phpspec/prophecy 1.7.3 requires phpdocumentor/reflection-docblock ^2.0|^3.0.2|^4.0 -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].
        - Installation request for phpspec/prophecy 1.7.3 -> satisfiable by phpspec/prophecy[1.7.3].

It seems like the problem is while [`phpspec/prophecy` 1.7.0](https://github.com/phpspec/prophecy/blob/v1.7.0/composer.json#L21-L22) was fine with PHP 5.6, and pulled a version of [`phpdocumentor/reflection-docblock` that was equally chill](https://github.com/phpDocumentor/ReflectionDocBlock/blob/3.0.3/composer.json),  with older PHP versions, [more recent versions](https://github.com/phpspec/prophecy/blob/v1.7.2/composer.json#L22) pull in `phpdocumentor/reflection-docblock` 4.0, which is [not chill](https://github.com/phpDocumentor/ReflectionDocBlock/blob/4.1.1/composer.json#L13) with older version of PHP.   

Caveats: Composer dependency rules are not my strong suit, and I'm not sure why my travis build from 15 days ago grabbed `phpspec/prophecy` 1.7.0 when it (looks like?) 

Before I spend more time on this -- would you be open to a change in the 1.7.x version tree that would help fix this?  I realize it's super easy with this dependency hell stuff to say "it's the other project", but if I ran into this I imagine some other PHP Unit users probably did as well. While PHP 7 is the new hotness, 5.6 still has a year of official support.

Finally -- if the answer is "No, this isn't a priority for us", knowing that sooner rather than later would still be helpful (so I can focus on other solutions).

Thanks for your time/attention.

**Comment by sstok** [comment]
Can you run `composer why phpdocumentor/reflection-docblock` because according to the version constraints used by prophecy it also allows older versions.

It seems another package is enforcing a higher version 🤔

**Comment by ciaranmcnulty** [comment]
That PR includes a new composer.lock - is it possible the PR author ran composer update using PHP 7?

**Comment by ciaranmcnulty** [comment]
In fact that PR modifies composer.lock to mandate the incompatible version of the library:
https://github.com/astorm/pestle/pull/318/files#diff-1da2c7edc898c70e5a79a9997c98ceccR1038

It’s almost certain that update has been run on a machine that isn’t using PHP 5.6

**Comment by astorm** [comment]
@sstok @ciaranmcnulty Thank you both and apologies for the time waster.  I'll be sitting here with my face in my palm for a bit.

**Comment by ciaranmcnulty** [comment]
Don’t worry, I was only able to diagnose it because I’ve made the same mistake in the past
