### ISSUE TITLE
Report unused mocked methods

### ISSUE THREAD

**Issue by meridius** [phpspec/prophecy#384]
Is there a way for PHPSpec or Prophecy to report unused mocked methods? I mean those specified using `$mockedObject->willReturn()` method.

**Comment by jakzal** [comment]
Short answer is no.

If mock expectations are not met the test will fail.

You're talking about stubs though.  Stubs don't need to be called during the execution. There's no way of reporting them as it shouldn't matter if a stub is called or not. If it matters, than the stub should be probably converted to a mock (by specifying call expectations with should(Not|)BeCalled).

**Comment by stof** [comment]
`willReturn` indeed does not describe any expectation about the method needing to be called. `shouldBeCalled` is what you need if you require the method to be called.

**Comment by meridius** [comment]
OK, thank you.
