### ISSUE TITLE
Mock two times same method with different type promises

### ISSUE THREAD

**Issue by zzenmate** [phpspec/prophecy#385]
How can I mock method two times with different promises?
For example, first promise should be ClientException, second should be Response.

**Comment by Taluu** [comment]
You have to add your own `methodProphecy` for that. But IMO this shows a problem in how you are handling things.

**Comment by jon-acker** [comment]
If you are talking about having a mock return different responses on subsequent calls you can do something like this:
https://github.com/phpspec/prophecy#method-prophecies-idempotency
But as Taluu says, the fact that you need to do this might indicate that you want two separate specs, one where there's an exception throw, the other a response is returned.
