### ISSUE TITLE
Methods type hinted as void in PHP 7.2 fail

### ISSUE THREAD

**Issue by crellbar** [phpspec/prophecy#397]
Methods type hinted as void in PHP 7.2 fail to have any expectation of a call when used as a Fake.

## Fake unexpected call

```
class SomeThing {
    public function doAThing(): void
    {}
    public function doOtherThing(): int
    { return random_int(0,10); }
}
```

```
class UsesSomeThing {
    function useIt(SomeThing $something) {
        $something->doOtherThing();
        $something->doAThing();
    }
}
```

Given the classes above one would expect to be able to create the Fakes below:

```
    $something = $this->leaderboardRepository = $this->prophesize(SomeThing::class);
    $this->leaderboardRepository->doOtherThing();
    $this->leaderboardRepository->doAThing();

    $usesSomething = new UsesSomeThing;
    $usesSomething->useIt($something->reveal());
```

The fake for `doOtherThing` does get called correctly but when the call is made to the `doAThing` method there is no expectation so prophecy fails with an `UnexpectedCallException`.

There is a workaround which I'm currently using which is to do the following in the test, but this is a bit misleading as it's no longer really a Fake and is inconsistent with how other Fakes are implemented:
```
    $something = $this->leaderboardRepository = $this->prophesize(SomeThing::class);
    $this->leaderboardRepository->doOtherThing();
    $this->leaderboardRepository->doAThing()->will(function(){}); // NOTE CALL TO will()

    $usesSomething = new UsesSomeThing;
    $usesSomething->useIt($something->reveal());
```

The proposed fix will mean that such workarounds are not needed and void fakes work as expected.

**Comment by jakzal** [comment]
Since you wrote a fake "manually", you don't need prophecy:

```
$usesSomething = new UsesSomeThing;
$usesSomething->useIt(new SomeThing());
```

However, I find it unfriendly that prophecy doesn't use return types to return a value of appropriate type.
