### ISSUE TITLE
Add ^5 to allowed versions of phpdocumentor/reflection-docblock

### ISSUE THREAD

**Issue by paulcdejean** [phpspec/prophecy#415]
Version 5 of reflection-docblock is coming out soon, and currently code that uses its new features will not be compatible with prophecy.

**Comment by stof** [comment]
What are the BC breaks in version 5 ?

**Comment by paulcdejean** [comment]
I forced prophecy on to version 5 with a composer require inline alias, and phpunit still worked. So I'd say that things are likely still compatible.

Not sure about BC breaks. Only documented changes in version 5 so far are:

* bump to PHP 7.1 minimum
* add strict typing
* bump type-resolver dependency to newest alpha
* fix init issue with example tag

**Comment by f3l1x** [comment]
Looking forward to it. 👍

**Comment by DonCallisto** [comment]
I can't find any `UPDATE` file describing what are the changes.
If new major version has only those changes is safe to bump the version, at least for what I see.
Moreover I'm not sure they're gonna make a good move  releasing a new major: I would have prefer a minor here.

**Comment by ricpelo** [comment]
Any news?
