### ISSUE TITLE
TypeError: Return value of class::functionName() must be an instance of /Interface, null returned

### ISSUE THREAD

**Issue by Youv** [phpspec/prophecy#426]
```php
class classname()
{
  public $var;

public functionName : Interface
{

   return $this->var;

}

}
```

**Comment by stof** [comment]
Well, constructing your object here allows to break your own contract, as the `var` property contains `null`. that's not a Prophecy bug. That's a bug in your class.

**Comment by Youv** [comment]
Oh! may i know... how to write testcase for a return type of a method is interface type..like

$this->method->willreturn(string)->ofTypeInterface...something like this?
