### ISSUE TITLE
Deprecation warning on PHP7.4 for ReflectionType::__toString

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/prophecy#444]
As in title; found when running Phpspec test suite (which currently treats deprecations as fails)

**Comment by ddziaduch** [comment]
@ciaranmcnulty I am on it 👌🏻

**Comment by ddziaduch** [comment]
@ciaranmcnulty seems that this is already fixed in revision `4ab322a2b7f4121062b23424ef071e4315ca342c` 🙃

**Comment by gep** [comment]
> @ciaranmcnulty seems that this is already fixed in revision [4ab322a](https://github.com/phpspec/prophecy/commit/4ab322a2b7f4121062b23424ef071e4315ca342c) 🙃

Closing the issue?
