### ISSUE TITLE
Improve auto IDE support of reveal

### ISSUE THREAD

**Issue by mpoiriert** [phpspec/prophecy#448]
I am using PHPStorm and using prophecy (via PHPUnit) cause a lot of warning because on wrong argument when using the reveal return value directly.

What I end up doing it this:

```PHP

$prophecy = $this->prophesize(Connection::class);
// ...
/** @var Connection $connection */
$connection = $prophecy->reveal();
$object = new Object($connection);
```
To do this a bit "cleaner" a and using the phpstorm.meta this could be change to

```PHP

$prophecy = $this->prophesize(Connection::class);
// ...
$object = new Object($ $prophecy->reveal(Connection::class));
```
This work but I have a warning because the reveal method doesn't have any argument.

Adding a file .phpstorm.meta.php with this would solve that
```PHP
<?php namespace PHPSTORM_META {

    $STATIC_METHOD_TYPES = [
        \Prophecy\Prophecy\ObjectProphecy::reveal('') => [
            "" == "@",
        ],
    ];
}

namespace Prophecy\Prophecy {
    class ObjectProphecy
    {
        public function reveal(string $class = null)
        {

        }
    }
}
```

**Comment by sstok** [comment]
Given you use PHPUnit, this plug-in might help you : https://plugins.jetbrains.com/plugin/9674-phpunit-enhancement/ 👍

**Comment by ciaranmcnulty** [comment]
@mpoiriert  I don't know how phpstorm does this, you're saying we can add this to our project and it'll be found in the vendor folder?

**Comment by mpoiriert** [comment]
@ciaranmcnulty Yes exactly. I tested it by putting this file manually in the vendor/phpspec/prophecy direcoty and it worked.

You can read about it here https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/

But the plugin that @sstok mention is working great. So it might be better to recommend it on the ream me documentation instead of adding the file...

**Comment by danepowell** [comment]
PhpStorm handles Prophecy objects natively now (pretty well, [not perfectly](https://youtrack.jetbrains.com/issue/WI-68395/Do-not-report-Void-method-result-used-for-PhpSpec-Prophecy-test-calls)). I'm not sure what value that plugin adds. Maybe this issue can be closed.

**Comment by mpoiriert** [comment]
No body seems to care and I am not using prophecy anymore so I will close it.

**Comment by stof** [comment]
We indeed solved this by using generics, which makes it work for any static analysis tool supporting them instead of only solving it for phpstorm.
