### ISSUE TITLE
Cannot handle DateTime dummies

### ISSUE THREAD

**Issue by elvetemedve** [phpspec/prophecy#454]
# Summary

When you want to use `\DateTime` object in **PHPSpec** tests as dummy object, then the test fails with the following error message:
```
err:Error("Call to a member function sub() on null")
```

## The Problem

Let's suppose we have two classes `Subject` and `Collaborator` and we are writing spec for the former.
Source code looks like this:
```php
<?php
// spec/SubjectSpec.php

namespace spec;

use PhpSpec\ObjectBehavior;
use Subject;

class SubjectSpec extends ObjectBehavior
{
    function it_can_handle_date_time_dummies(\DateTime $date, \Collaborator $c)
    {
	$this->beConstructedWith($c);

	$c->takeADate($date)->willReturn(true);

        $this->doSomething($date)->shouldReturn(true);
    }
}
```

```php
<?php
// src/Subject.php

class Subject
{
    private $c;

    public function __construct(Collaborator $c)
    {
        $this->c = $c;
    }

    public function doSomething(\DateTime $date)
    {
    	return $this->c->takeADate($date);
    }
}
```

```php
<?php
// src/Collaborator.php

interface Collaborator
{
    public function takeADate(\DateTime $date);
}
```

_composer.json_
```json
{
    "name": "gbuza/spec-test",
    "authors": [
        {
            "name": "Géza Búza",
            "email": "bghome@gmail.com"
        }
    ],
    "require": {
        "phpspec/phpspec": "^6.1"
    },
    "autoload": {
        "psr-0": {
            "": "src"
        }
    }
}
```

Finally execute the tests: `vendor/bin/phpspec run`

### Actual Result

```
Subject                                                                         
  10  - it can handle date time dummies
      exception [err:Error("Call to a member function sub() on null")] has been thrown.

                                      100%                                       1
1 specs
1 example (1 broken)
```

### Expected Result

```
1 specs
1 example (1 passed)
```

## Explanation

Prophecy uses the `DateTimeComparator` class from `sebastian/comparator` package from the `ExactValueToken` class in order to compare the actual date argument with the argument of the promise object. That worked fine before [2.1.1](https://github.com/sebastianbergmann/comparator/blob/2.1.1/src/DateTimeComparator.php) or earlier versions. But in [2.1.2](https://github.com/sebastianbergmann/comparator/blob/2.1.2/src/DateTimeComparator.php#L53-L55) methods of the `\DateTime` class are chained like `$expected->setTimezone()->sub()`. Since `$expected` is not a real `\DateTime` object, but actually a dummy test double, all of the methods will return `null` by definition. Therefore `$expected->setTimezone()` becomes `null`, that's why `sub()` cannot be called on that.

Since our compared object is not a real `\DateTime`, it should not be compared by the `DateTimeComparator`. The condition to support an object is to [check the inheritance chain](https://github.com/sebastianbergmann/comparator/blob/2.1.2/src/DateTimeComparator.php#L26-L30), it will be accepted for comparison which is fine when the real `\DateTime` class is extended.

**Comment by stof** [comment]
As DateTime is a value object, I would suggest using an actual one instead of mocking it (and otherwise, you have to configure the mock to actually behave like the PHP class, which is your responsibility if you create a mock for it, which is the main reason for the common saying "don't mock what you don't own")

**Comment by stof** [comment]
This is not something that can be fixed in prophecy as prophecy cannot autoconfigure a mock to behave like the actual class (as it does not know how it is supposed to behave).
