### ISSUE TITLE
1.10.0 weird problem with callables?

### ISSUE THREAD

**Issue by acasademont** [phpspec/prophecy#458]
Hi, we just noticed some strange failing tests after upgrading to 1.10.0. We isolated the problem to this test case. 

```php
require __DIR__ . '/vendor/autoload.php';

class A {
    public function calc(callable $callable): int
    {
        return 0;
    }
}

$prophet = new \Prophecy\Prophet();

$callable = function() {};
$a = $prophet->prophesize(A::class);
$a->calc($callable)->willReturn(1);

var_dump($a->reveal()->calc($callable));
```

with 1.9.0, the output is `int(1)`
with 1.10.0 there's a fatal error

```
PHP Fatal error:  Uncaught TypeError: Return value of Double\A\P1::calc() must be of the type int, null returned in /Users/albert/Projects/backend-app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code:6
Stack trace:
#0 /Users/albert/Projects/backend-app/test_prophecy.php(18): Double\A\P1->calc(Object(Closure))
#1 {main}
  thrown in /Users/albert/Projects/backend-app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 6

Fatal error: Uncaught TypeError: Return value of Double\A\P1::calc() must be of the type int, null returned in /Users/albert/Projects/backend-app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code:6
Stack trace:
#0 /Users/albert/Projects/backend-app/test_prophecy.php(18): Double\A\P1->calc(Object(Closure))
#1 {main}
  thrown in /Users/albert/Projects/backend-app/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 6
```

we're using PHP 7.3.13.

The problem seems to be related somehow to the callable, it does not happen if the function argument is a scalar or an object. Any ideas? Thx!!

**Comment by adriansuter** [comment]
I can confirm that behaviour. See https://github.com/slimphp/Slim/issues/2901#issuecomment-567458575. If we use `Argument::is($callable)`, then this works again.

**Comment by ciaranmcnulty** [comment]
I've reproduced and it seems to be caused by this change to how we match arguments exactly:
https://github.com/phpspec/prophecy/commit/e9e0970d95037b00fe980bb71877fc6c4f84f0c2

I suspect we're treating the method as un-stubbed because matching the two callables isn't working

(ping @scroach)

**Comment by ciaranmcnulty** [comment]
Hm, #456 tried to fix this but I missed it in the churn because it was closed again
