### ISSUE TITLE
[RFC] More verbose UnexpectedCallException

### ISSUE THREAD

**Issue by sstok** [phpspec/prophecy#46]
The UnexpectedCallException message is not very helpful when only passing one object whose properties don't equal.

I actually copied the export() method from PHPUnit to get a more verbose message without recursion problems.

https://github.com/sstok/prophecy/commit/2bb8cf07ebcdf05dfdee96bea3293982626db1f6

As PHPUnit is BSD 3 licensed and this actual idea needs to be discussed further I did not open a PR.

**Comment by srosato** [comment]
Have we got any news on this? I too find that the message is not verbose enough when comparing value objects or arrays.

**Comment by sstok** [comment]
I'm not sure if this is still relevant, IIRC the diff is more verbose now. Closing.
