### ISSUE TITLE
Drop older versions

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/prophecy#475]
I started looking at PHP8 support and don't think it's possible to maintain support across 2 major versions.

I'm sold on upping the PHP version in the next minor, but what to? 7.0, 7.2 or 7.4?

@stof, opinion?

**Comment by ciaranmcnulty** [comment]
Instinct says 7.4...

**Comment by stof** [comment]
IMO, we need to keep support at least for the maintained PHP versions (meaning that going 7.4+ might be too early).

Then, the question is what each dropped version gives us (both in term of PHP features that become usable, and in terms of versions of dependencies).
For instance, from a PoV of PHP features, PHP 7.3 does not really give much benefit compared to PHP 7.2. The bigger features are in 7.4.

**Comment by ciaranmcnulty** [comment]
@stof Yeah as you can see in #476 there aren't any version checks for 7.3 which means

Looking forward to supporting 8.0 as well, most important thing is that we shoulddrop any versions that don't have replacements for the deprecated APIs in 8.0. I think that's actually only 7.1

I guess I'm happy making it 7.2 and sticking to the PHP supported version. Shall I update the PR to be 7.2?
