### ISSUE TITLE
No longer worry about argument types?

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/prophecy#488]
Since PHP 7.2 a child class can drop type hints from arguments

We could conceivably remove a lot of prophecy code (and edge cases!) by generating doubles without argument type hints.

Return types would still need to be maintained.

The only place I can think of where this would be harmful would be if the double was then reflected

**Comment by stof** [comment]
This would have a big drawback: calling the double with invalid types of arguments would not trigger a TypeError anymore, making the tests using that double a lot less reliable.

**Comment by ciaranmcnulty** [comment]
Aaaah damn you're right
