### ISSUE TITLE
static closure callback fails with CallbackPromise

### ISSUE THREAD

**Issue by mathroc** [phpspec/prophecy#506]
Using static callbacks with CallbackPromise fails once Prophecy tries to bind the object to the callback closure

The following code:

$someProphecy->someMethod()->will(static fn () => 1);

Will fails with: 

> Cannot bind an instance to a static closure

Anonymous functions without the static keyword are working as expected

I don’t know how to check that a closure is static though

**Comment by ciaranmcnulty** [comment]
I don’t know a way of seeing via reflection, I guess it’d be a case of trying to bind and catchii you by the specific Error?

**Comment by ciaranmcnulty** [comment]
Actually it looks like you can check if `(new ReflectionFunction($closure))->getClosureThis()` is `null`
