### ISSUE TITLE
Mocking symfony's `ValidatorInterface` results in "wrong" mock instance

### ISSUE THREAD

**Issue by cjost1988** [phpspec/prophecy#513]
Hi,

I am trying to mock `ValidatorInterface` https://github.com/symfony/validator/blob/5.x/Validator/ValidatorInterface.php and inject it into a service that is depending on a class instance implementing this interface.

Following error occurs and I don't really understand it:
```
__construct() must be an instance of Symfony\Component\Validator\Validator\ValidatorInterface, instance of Double\stdClass\P1 given, called in
```

I tried to find some information on the internet but that wasn't successful.

Thanks in advance.

Cheers,
Chris

**Comment by stof** [comment]
Can you share a reproducer ?

**Comment by ciaranmcnulty** [comment]
The error indicates that prophecy didn’t know what class to double

**Comment by cjost1988** [comment]
Thanks for your responses. Sadly this issue does not occur with a brand new installation of symfony 3/4/5 - I've tested them all.
I will now try to identify why this is happening in existing projects. I guess it's related to a dedicated component installed.

**Comment by ptdias25** [comment]
i'm facing the same problem, some mocks work others don't

**Comment by ciaranmcnulty** [comment]
@ptdias25 any chance you could share some code that reproduces it?

**Comment by ptdias25** [comment]
> @ptdias25 any chance you could share some code that reproduces it?

the error was on my side, sorry :X
