### ISSUE TITLE
Mocking Class / Interface with @method __unserialize ( array $data ) doc block throws fatal error in PHP8

### ISSUE THREAD

**Issue by BolZer** [phpspec/prophecy#520]
Hi,

sorry in advance if this issue came already around but i didn't see any related issue on the first several pages.
I'm pretty sure that this issue is fairly new.

## Example Repository
https://github.com/BolZer/prophecy_php_8_issue

## The Problem
If you prophesize a class or interface which holds a php doc block annotation as follows:

```php
/**
 * @method void __unserialize(array $data)
 */
class Test
{}
```

PHP 8 will throw a fatal error if you access the mock / double. The thrown error:

`PHP Fatal error:  Method Double\Fixture\Test\P1::__unserialize() must take exactly 1 argument in /{retracted}/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 11`

**You get this error if you checkout my example repository and run the example.php script.**

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Fixture\Test;
use Prophecy\Prophet;

$prophet = new Prophet();

$mock = $prophet->prophesize(Test::class);

$mock->getTestValue()->willReturn("Not Test");
```

This is not the case in PHP 7.4. I've tested the same code with different PHP Versions.
The generated Code in `Prophecy\Doubler\Generator\ClassCreator` is identical and is as follow:

```php

namespace Double\Fixture\Test {
    class P1 extends \Fixture\Test implements \Prophecy\Prophecy\ProphecySubjectInterface, \Prophecy\Doubler\Generator\ReflectionInterface
    {
        private $objectProphecyClosure;

        public function getTestValue():
        string
        {
            return $this->getProphecy()
                ->makeProphecyMethodCall(__FUNCTION__, func_get_args());
        }

        public function __construct()
        {

        }

        public function __unserialize()
        {
            return $this->getProphecy()
                ->makeProphecyMethodCall(__FUNCTION__, func_get_args());
        }

        public function __call($name, $arguments)
        {
            throw new \Prophecy\Exception\Doubler\MethodNotFoundException(sprintf('Method `%s::%s()` not found.', get_class($this), func_get_arg(0)), get_class($this), func_get_arg(0));
        }

        public function setProphecy(\Prophecy\Prophecy\ProphecyInterface $prophecy)
        {
            if (null === $this->objectProphecyClosure) {
                $this->objectProphecyClosure = static function () use ($prophecy) {
                    return $prophecy;
                };
            }
        }

        public function getProphecy()
        {
            return \call_user_func($this->objectProphecyClosure);
        }

    }
}
```

The issue is that the __unserialize function gets mocked without arguments.  My assumption is that in php7.4 a notice is thrown but the execution won't come to a halt. 

## Discovery

I have encountered this problem at my work. We are currently upgrading PHP to version 8 and several of our unit test fail with segmentation faults or the error described above. I was able to determine fairly quickly that the problem was related to an interface from the Symfony framework. The interface I am referring to is the TokenInterface. This interface has the same annotation which I describe here.

I was able to get the tests running again quickly by replacing the interface with a concrete implementation.

I think the problem here is with Prophecy and how the stub for the method is generated.

If you have any questions or need help, please let me know.

**Comment by ciaranmcnulty** [comment]
I think this will be an issue for all magic methods used in `@method` - since PHP 8 magic method signatures have been enforced (https://wiki.php.net/rfc/magic-methods-signature)

Prior to this, we've handled `@method` by generating a method with no arguments. Because PHP has always taken extra arguments this hasn't been an issue, and prior to the PHP 8 change there was no contract that these `@method` annotations could have broken

I think we'd need to either:

a) read the arguments from the `@method` docblocks and make sure the generated methods conform,
b) add some special cases for what arguments magic methods take
c) handle `@method` some other way e.g. by generating `__call` instead
