### ISSUE TITLE
Call to undefined method Prophecy\Argument::in()

### ISSUE THREAD

**Issue by tyteen4a03** [phpspec/prophecy#522]
Unlike other functions in `Argument`, `in()` and `notIn()` are not static methods, causing an error when trying to call it statically. 

It should be changed to static to be in line with other methods.

**Comment by tyteen4a03** [comment]
@stof I have no problem doing a PR but I'm just wondering if this would constitute an API breaking change? (I can also keep both in and deprecate the non-static one.)

**Comment by ciaranmcnulty** [comment]
We've only ever documented static calls and it's clearly an error so I'd count it as a bug fix
