### ISSUE TITLE
PHP 8.1 support / composer

### ISSUE THREAD

**Issue by alecpl** [phpspec/prophecy#531]
```
- phpunit/phpunit[9.4.1, ..., 9.5.7] require phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[1.12.1, 1.12.2, 1.13.0].
...
- phpspec/prophecy[1.12.0, ..., 1.13.0] require php ^7.2 || ~8.0, <8.1 -> your php version (8.1.0-dev) does not satisfy that requirement.
```
It would be nice if we could test our code before the 8.1.0 is released.

**Comment by BenMorel** [comment]
+1. This library being a dependency of PHPUnit, most open-source libraries can't be tested on PHP 8.1 before Prophecy is declared compatible.

Now that PHP 8.1 entered beta, I'm eager to test my libraries against it.

Looking forward to #533 being merged & released!

**Comment by chris-doehring** [comment]
I suggest to reopen this issue since there is no php 8.1 release, yet. For those who want to know about the current status:

https://github.com/phpspec/prophecy/pull/533#issuecomment-895854748
> I've added some issues for things we'll need to check on PHP 8.1
> 
> https://github.com/phpspec/prophecy/issues?q=is%3Aopen+is%3Aissue+label%3APHP8.1
> 
> Any extra issues people can think of, please raise them
