### ISSUE TITLE
static unknown class

### ISSUE THREAD

**Issue by iaicam** [phpspec/prophecy#532]
I made the following change

```diff
-    public static function createForUser(UserInterface $user, string $email): self
+    public static function createForUser(UserInterface $user, string $email): static
```

And I got 

```
Fatal error: '\static' is an invalid class name in /opt/atlassian/pipelines/agent/build/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 58
```

I would expect it to treat static roughly the same way it treats self.

**Comment by ciaranmcnulty** [comment]
It looks like we're prefixing static with a `\`, which is what we do for classes. 

I think this should be added as an exception like we do for `void` here https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Doubler/Generator/Node/ReturnTypeNode.php#L11

**Comment by dpi** [comment]
Looks like this may be a dupe of #527

**Comment by iaicam** [comment]
Yep. I'll close
