### ISSUE TITLE
Allow PHP 8.2

### ISSUE THREAD

**Issue by ricardoboss** [phpspec/prophecy#550]
Hi! I want to test code using nightly builds of PHP 8.2. Will you be adding an experimental branch or do we have to wait until a release candidate is ready?

**Comment by stof** [comment]
Composer 2.2 added a feature to solve that case: `--ignore-platform-req=php+`. The `+` indicates to ignore the upper bound of the requirement only, which is precisely what you need when you want to test nightly builds of PHP.

**Comment by ricardoboss** [comment]
Thanks! That did the trick.
