### ISSUE TITLE
Support for readonly classes

### ISSUE THREAD

**Issue by stof** [phpspec/prophecy#559]
https://wiki.php.net/rfc/readonly_classes

**Comment by kschatzle** [comment]
@stof anyone working on the PHP8.2? Don't want to duplicate work, but I can pick these up.

**Comment by kschatzle** [comment]
Was playing around with this idea.  Essentially make the underlying "testing" class be capable of being readonly. Can't be sure if this is a good idea, just playing with it.

https://gist.github.com/kschatzle/5394a3abc427659d21ef6f854e01c0f6

**Comment by stof** [comment]
@kschatzle not that I'm aware off.

**Comment by stof** [comment]
Note that the initial compat with PHP 8.2 might be to have a clear error message saying that doubling a readonly class is not supported yet, in case supporting this case require more time.

**Comment by ciaranmcnulty** [comment]
Yeah I've not seen any activity on it so go ahead if you have the time

**Comment by kschatzle** [comment]
https://github.com/phpspec/prophecy/pull/564
