### ISSUE TITLE
Is support for hhvm dropped?

### ISSUE THREAD

**Issue by TysonAndre** [phpspec/prophecy#561]
I'm not currently using hhvm, but would be useful to clarify this in comments/issue tracker

https://hhvm.com/blog/2018/09/12/end-of-php-support-future-of-hack.html

HHVM 4.0 dropped support for php files in 2019
HHVM did not add support for new functions such as spl_object_id - see #560 (realized I saw a few comments in the codebase about HHVM and was surprised there was never an spl_object_id addition to HHVM)

- There are open issues related to hhvm, can they be closed?
- Can comments in the codebase related to hhvm be removed
- Tests don't seem to target hhvm

**Comment by stof** [comment]
Yes, we stopped supporting HHVM because we only support PHP and they dropped it. I will clean the issue tracker.

**Comment by jdreesen** [comment]
There are some references to HHVM in the code, too: https://github.com/phpspec/prophecy/search?q=hhvm

**Comment by stof** [comment]
The HhvmExceptionPatch should indeed be removed. Do you want to send a PR ?

**Comment by jdreesen** [comment]
I'm sorry, but I'm very busy at the moment. Maybe @TysonAndre can do it?
