### ISSUE TITLE
Chained methods should return self, is there any workarounds?

### ISSUE THREAD

**Issue by emircanerkul** [phpspec/prophecy#596]
Test File:
```php
    $query = $this->prophesize(QueryInterface::class);
    $this->entityStorage->getQuery()->willReturn($query->reveal());

    $entityTypeManager = $this->prophesize(EntityTypeManager::class);
    $entityTypeManager->getStorage('trophy')->willReturn($this->entityStorage->reveal());
```

I got `Call to a member function sort() on null` error. But it should return itself.

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/11430795/230770382-574aad07-cc9a-4162-ad46-cfff1ae7b536.png">

At the end execute method I'll override the data as needed but before this, I need to run chained methods which return themselves. How can I do that? Shouldn't this be done automatically?

**Comment by stof** [comment]
The issue here is that you don't configure what `Query::condition` should return (and as there is no native return type, it returns null by default)

**Comment by emircanerkul** [comment]
Okay, thank you
