### ISSUE TITLE
PHPUnit 10 compatibility, master is compatible but not the v1.17.0 tag…

### ISSUE THREAD

**Issue by shulard** [phpspec/prophecy#599]
Hello !

I work on a project where we are using both PHPUnit and PHPSpec. I can't upgrade to PHPUnit 10 because there is a conflict with the latest stable version of phpspec/prophecy which requires sebastian/recursion-context v4.

I viewed that the master branch is up to date and allows installing PHPUnit 10, do you think it might be possible to create a new release ? Is there some instability today on master that might block the release process ?

If so I can try to help fixing those issues… Let me know :smile:

**Comment by alexander-schranz** [comment]
Not a maintainer of this project but think at current case the best until it is released is what we can do, is to test if the current `master` versions works as expected by trying it out in our projects and give feedback if we stumble over some issues. For this you can currently use the `@dev` versions:

```bash
    "require-dev": {
        "phpspec/prophecy": "^1.18@dev",
        "phpspec/prophecy-phpunit": "^2.1@dev",
        "phpunit/phpunit": "^10.2"
    }
```

For paratest user also update to:

```bash
        "brianium/paratest": "^7.0",
```

is required.

**Comment by keradus** [comment]
@stof , I think it was you releasing last time. You think a new release of what is already merged is possible?

**Comment by jg-development** [comment]
+1

**Comment by jorgsowa** [comment]
Hello @stof. Do you need any help releasing a new version?

**Comment by stof** [comment]
1.18.0 has been released now

**Comment by keradus** [comment]
thanks @stof !


Unfortunately, I failed to install it because this one is not yet compatible (yet having v10 PR already merged, simply not released):
https://github.com/phpspec/prophecy-phpunit
