### ISSUE TITLE
phpspec/prophecy v1.17.0 requires sebastian/comparator ^3.0 || ^4.0 -> found sebastian/comparator[3.0.0, ..., 3.0.5, 4.0.0, ..., 4.0.8] but it conflicts with your root composer.json require (^5.0).

### ISSUE THREAD

**Issue by n-for-all** [phpspec/prophecy#606]
Can we update the packagist version?

https://packagist.org/packages/phpspec/prophecy

**Comment by alexander-schranz** [comment]
This has more todo with the PHPUnit 10 support.

PHPUnit 9 use  `sebastaon/comparator` : `4` which and currently `1.17.0` only supports PHPUnit 9.

The current `master` branch already supports PHPUnit 10 if you want to test it checkout this: https://github.com/phpspec/prophecy/issues/599#issuecomment-1649720948
