### ISSUE TITLE
SplFileObject generated code is syntax error on PHP8.2

### ISSUE THREAD

**Issue by reioto** [phpspec/prophecy#610]
TestCode is
```
$fileMock = $this->prophesize(SplFileObject::class);
$file = $fileMock->reveal();
```
Returned Error Message on PHP8.2:

```
ParseError: syntax error, unexpected token "{"

vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:137
vendor/phpspec/prophecy/src/Prophecy/Doubler/CachedDoubler.php:36
vendor/phpspec/prophecy/src/Prophecy/Doubler/Doubler.php:100
vendor/phpspec/prophecy/src/Prophecy/Doubler/LazyDouble.php:135
vendor/phpspec/prophecy/src/Prophecy/Prophecy/ObjectProphecy.php:118
```

Of course there are no syntax error in this package.
But I found it in the generated code.

```
public  function getChildren(): ? {
return $this->getProphecy()->makeProphecyMethodCall(__FUNCTION__, func_get_args());
}
```
So, `SplFileObject::getChildren()` is always returned null.
It's caused by a method that returns null In this case.

I think.
Part of what is causing this problem is here.
https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Doubler/Generator/ClassCodeGenerator.php#L89
The null is converted to "".

**Comment by reioto** [comment]
```
PHP Type declarations:
Changelog
8.2.0 | The types null and false can now be used standalone.
```
Probably false type too.

**Comment by stof** [comment]
Already fixed in the dev version by https://github.com/phpspec/prophecy/pull/598

**Comment by reioto** [comment]
Oh nice! thanks!
