### ISSUE TITLE
Support for mocking methods with "static" return type

### ISSUE THREAD

**Issue by aik099** [phpspec/prophecy#620]
When attempting to mock a method with a `static` return type (see https://php.watch/versions/8.0/static-return-type), then you'll get this error:

```
Prophecy\Exception\Prophecy\MethodProphecyException: Cannot create a return value for the method as the type "static" is not supported. Configure an explicit return value instead.
```

Code:
```php
class Process implements \IteratorAggregate
{
    public function mustRun(?callable $callback = null, array $env = []): static
    {
        return $this;
    }
}
```

**Comment by stof** [comment]
The error message does not say that mocking such methods is not supported. It says that guessing a return value is not supported and you need to configure an explicit one (for instance by using `->willReturnSelf()`)

**Comment by aik099** [comment]
> The error message does not say that mocking such methods is not supported. It says that guessing a return value is not supported and you need to configure an explicit one (for instance by using `->willReturnSelf()`)

That helped. Thanks.

What about the associated PR ( https://github.com/phpspec/prophecy/pull/621 ) to improve guessing code?

**Comment by aik099** [comment]
I'm getting an error, that `willReturnSelf` method isn't defined in the used Prophecy version. I've used this code instead:

```php
$mock = $this->prophesize('Process');
$mock->mustRun()->willReturn($mock)->shouldBeCalled();
```

is this correct way or I should be doing

```php
$mock = $this->prophesize('Process');
$mock->mustRun()->willReturn($mock->reveal())->shouldBeCalled();
```

instead?

**Comment by stof** [comment]
ah indeed. We don't have `willReturnSelf` in Prophecy (maybe I confused with PHPUnit mock or with a past discussion on Prophecy that has not been implemented).

The first code snippet is fine. `->willReturn` does not require revealing explicitly.

**Comment by aik099** [comment]
Great. Closing.
