### ISSUE TITLE
Mocking method with arguments passed by reference is not working.

### ISSUE THREAD

**Issue by gunnarlium** [phpspec/prophecy#78]
Have a look at this Gist: https://gist.github.com/gunnarlium/8d8f7ee43992476ea8e2

When trying to mock a method that take an array reference as argument, I get a PHP warning `PHP Warning:  Parameter 1 to {closure}() expected to be a reference, value given`, and the argument is not treated as a reference.

**Comment by Seldaek** [comment]
Duplicate of https://github.com/phpspec/prophecy/issues/225
