### ISSUE TITLE
Mocking variadic functions

### ISSUE THREAD

**Issue by stof** [phpspec/prophecy#91]
PHP 5.6 introduces variadic arguments for functions. Prophecy should be updated to support mocking such methods.

Note that I might provide a patch (unless someone beats be). I'm opening the issue here as a reminder

**Comment by bweston92** [comment]
Any update when this will be merged?

**Comment by sstok** [comment]
@whatthejeff Is there a PR for this? It seems you have a commit that adds this :)

**Comment by whatthejeff** [comment]
@sstok #143 :)

**Comment by RayRutjes** [comment]
Any news on this?

**Comment by ChadSikorra** [comment]
It would be nice to see this supported added. I've resorted to skipping some specs because of this.

**Comment by malkusch** [comment]
> I'm opening the issue here as a reminder

Let me remind you, it's still happening:

> Declaration of Double\test\Foo\P1::bar() should be compatible with test\Foo::bar(...$args)
