### ISSUE TITLE
High memory usage in phpspec because of repeated double definitions

### ISSUE THREAD

**Issue by acoulton** [phpspec/prophecy#96]
Hi,

I'm using phpspec and prophecy on a few projects, and the suite for one is now growing to a reasonable size with the result that today we started to hit out of memory errors during the suite run.

Our suite overall has 1205 examples and makes a lot of use of prophecy throughout, and I'm getting runtime of about 37 seconds and memory usage of about 178Mb.

I did some profiling and found that the biggest component is that prophecy generates a new double class definition for every mock - thanks to [the doubler](https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Doubler/Doubler.php#L120) and the [unique sequence number generated for each double](https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Doubler/Doubler.php#L120).

I don't think this should be necessary - surely the mocked class will always have the same methods and interfaces for duration of one suite run, so the double definition could just be built once?

I quickly experimented with removing the sequence counter and updating the doubler to do this:

``` php
        $name = $this->namer->name($class, $interfaces);
        if (class_exists($name, FALSE)) {
        return $name;
        }
        // otherwise continue as before to define and create the double
```

Suite runtime was reduced to 22 seconds (just over 50%) and memory usage to 50Mb (a quarter). 

The only issue I hit was this change also means that some == comparators in ExactValueToken, ObjectStateToken and ObjectProphecy encounter a recursive property and fail with a fatal during the comparison. Switching them to === works, but is obviously not appropriate for the matchers at least. 

It looks like this is because previously the doubles nested within those method prophecies and argument wildcards had different classes so == never had to recurse into comparing their properties, and now that it does it gets caught on the circular references between double and doubler. I can investigate further and look for a BC fix.

Before I spend more time on this, though, I wanted to check with those who know more:
- is there a reason for generating the double class each time that I'm not aware of?
- would you accept a fix along these lines into the project given appropriate tests and backwards compatability?

I saw that there is also a (currently unused) CachedDoubler implementation - which has the same issues with recursive property comparison - but this obviously then means managing an instance of that everywhere and passing it into Prophet instances. Since the existence or not of a class is part of global state anyway, it feels more logical to me just to generate the same name for each type of double and use class_exists to manage it.

**Comment by DonCallisto** [comment]
Problem with `CachedDoubler` and `==` is that `Double` has `ObjectProphecy` in itself and `ObjectProphecy` has the double inside so we have a circular reference.
BTW `CachedDoubler` or `Doubler` is not a problem for `==` comparison. 
We don't fall into that recursion with `Doubler` only because, for `Double` naming convention we don't go inside property comparison as class (name) is not the same so we never hit that code.

**Comment by DonCallisto** [comment]
To all interested, take a look at https://github.com/phpspec/prophecy/pull/420
